### ISSUE TITLE
Active State

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#141]
Looks like somewhere along the way the "active state" stopped working with components. Could we get that adjusted so that the page I'm on displays grey in the nav bar again?

![image](https://cloud.githubusercontent.com/assets/26605197/24976751/e7b1f9d2-1f87-11e7-9ce6-836641638539.png)

**Comment by Aleniras** [comment]
Also, it would appear the search bar is not quite aligned..?

**Comment by kebowdog** [comment]
These look like issues with the Wordpress theme, not the components. If you look at the components demo page the search and the active state are both working.

**Comment by kebowdog** [comment]
I'll add a CSS selector for active as well as selected.
