### ISSUE TITLE
[BYU-HEADER] BYU logo needs to link to respective sites homepage

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#142]
If I'm on BYU Brand, the logo should take me to BYU Brand homepage. If I'm on BYU Math, the BYU logo should take me to BYU Math homepage. etc. 

Looks like right now only the text next to it links.

![image](https://cloud.githubusercontent.com/assets/26605197/24984041/3ad63392-1fa8-11e7-9d99-7eb949c98451.png)

**Comment by ThatJoeMoore** [comment]
This request is a bit hairy.  We'll need to discuss how to accomplish it in our next engineering meeting.

**Comment by kebowdog** [comment]
It was decided that we'd make this an attribute called 'home-url'.

**Comment by bmorgan296** [comment]
Implemented in PR #223.
