### ISSUE TITLE
Documentation pages should include font-awesome

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#148]
# One-Line Summary
The social media icons need font-awesome, so we should include that link in the docs.
Also, is the font link in the docs the full font package or the lite package?

**Comment by rburkey87** [comment]
@ThatJoeMoore's comment from the previous PR - "We are NOT requiring Fontawesome for use with the theme. If there is still something requiring it, we need to change that."

**Comment by kebowdog** [comment]
@ThatJoeMoore is working on moving the social media icons to a separate repo, so this will no longer be relevant. I'll close this once that's working.
