### ISSUE TITLE
P's and q's have tails cut off in site title

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#150]
# One-Line Summary
The line height of 22px is cutting off the tails of descending letters like ps and qs

For an example look at the "P" on http://2017-components-demo.cdn.byu.edu/

![image](https://cloud.githubusercontent.com/assets/19493582/25030381/dd59f94e-2081-11e7-96b6-0f70df8e336c.png)

**Comment by morrisonlevi** [comment]
For what it is worth on Chrome on Linux simply removing the line-height fixed the issue with no obvious defects.

**Comment by kebowdog** [comment]
That works fine for single-line titles, but for two-line titles or subtitles we'll need to do a little extra tweaking of the margins so they still align correctly with the top and bottom of the BYU logo.

**Comment by kebowdog** [comment]
Addressed by PR #161

**Comment by Aleniras** [comment]
Also having problems with header and subhead running into each other.  

![image](https://cloud.githubusercontent.com/assets/26605197/25627671/9edc006a-2f20-11e7-9e0f-f2e46896f363.png)

**Comment by rburkey87** [comment]
It looks like I don't have this issue in Drupal, but in the HTML build, it seems to fix the issue for single-line titles if you remove the margin adjustments. However, that seriously screws things up for titles with sub-titles... 
`.byu-header-root .byu-header-primary .byu-header-title ::slotted(*) {`
    `font-family: Vitesse A,Vitesse B,Georgia,serif!important;`
   ` /* margin-top: -1px; */`
   ` /* margin-bottom: -1px; */`
}`

@aleni - we'll be able to look at the header/subhead collision once the overriding styling is removed. As of now, it's adding font-weight, etc that should be there, so this will be addressed next.

**Comment by ThatJoeMoore** [comment]
I've reviewed what's currently in master, and it appears that this really was resolved by #161.  The fix will be rolling out this Wednesday as part of version 1.0.1.
