### ISSUE TITLE
Blue underline appearing under mobile search

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#152]
Can we eliminate the blue underline appearing under the mobile search bar?  I've attached two examples (one with, one without). Perhaps it is only occurring in the drupal theme? Do we have any other websites we can check?

![img_1150](https://cloud.githubusercontent.com/assets/26605197/25054901/f07c2506-211c-11e7-91d3-ddc9abf87563.PNG)
![img_1151](https://cloud.githubusercontent.com/assets/26605197/25054902/f093f500-211c-11e7-8e1a-fc513260f1c8.PNG)

**Comment by ThatJoeMoore** [comment]
Fixed in #175
