### ISSUE TITLE
Documentation need to switch <h1> to <span> for title

### ISSUE THREAD

**Issue by Jonathan-Snyder** [byuweb/byu-theme-components#153]
# One-Line Summary
<h1> tag needs to be replaced with <span> tag for the site title

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
http://2017-components-demo.cdn.byu.edu/index.html
# Issue Type
Typo
*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
Change the documentation on the page above to have a span tag rather than an h1 tag. The h1 causes the title to be way too big.
**If the issue is with styling, please include screenshots!**

**Comment by smoosh911** [comment]
If we get the styles working just right, this issue will be fixed by issue #154.
