### ISSUE TITLE
README.md has wrong demo URL

### ISSUE THREAD

**Issue by pauldeden** [byuweb/byu-theme-components#155]
# One-Line Summary

http://2017-core-components.cdn.byu.edu/ is down

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers
**All browsers are affected**
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

**Comment by ThatJoeMoore** [comment]
@pauldeden Where did you get that URL?  The correct one is http://2017-components-demo.cdn.byu.edu/

**Comment by pauldeden** [comment]
It's in the README.md

**Comment by pauldeden** [comment]
I can make a pull request if you want to fix it.

**Comment by ThatJoeMoore** [comment]
That would be great.  Thanks!

**Comment by pauldeden** [comment]
done
