### ISSUE TITLE
Mobile Menu Search

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#158]
Mobile menu search bar should not appear when the mobile menu is expanded, like in the spec sheet. If this fix is going to take some time to figure out, lets at least move it to the bottom of the expanded menu rather than the top. (See admissions).  

![image](https://cloud.githubusercontent.com/assets/26605197/25203806/e4b5361e-2517-11e7-9583-b3c9c2324b26.png)

**Comment by ThatJoeMoore** [comment]
The plan is to have the search bar shrink as the menu bar expands.  This hides the search bar, while not having as much animation jank.

**Comment by rburkey87** [comment]
Transition applied in the `mobile-search` branch. Waiting for input on animation before submitting PR.

**Comment by bmorgan296** [comment]
At then engineering meeting on 7/11/17, we reviewed the different animations as a committee and decided to discuss with @Aleniras what some alternatives may be. I am replacing the 1.1.1 tag with 1.1.2 to give us time to talk with the design group.

**Comment by bmorgan296** [comment]
In the engineering meeting on 8/1/2017, we decided to use the animation that @rburkey87 created, but git rid of the flash of blue.

**Comment by bmorgan296** [comment]
Fixed in #263
