### ISSUE TITLE
Drupal Theme Adjustments

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#159]
- Add padding left of sign in icon so it aligns with S in search

- Align all links on the same line (see specifically "action" item at the bottom of the menu should match left alignment of all the other links.)

- Action items should appear blue (see original below)

- Blue line appearing beneath search bar (also mentioned in it's own issue)

- Action buttons in desktop should be 500 weight

- Links should be centered even in hover (see desktop view attached)

- Page I am currently on should show in active state (currently shows nothing)

![image](https://cloud.githubusercontent.com/assets/26605197/25251950/6c45a9fe-25d8-11e7-8a98-412de939fd99.png)

![image](https://cloud.githubusercontent.com/assets/26605197/25252324/c51203b0-25d9-11e7-966e-47a7efdaaa55.png)

![image](https://cloud.githubusercontent.com/assets/26605197/25255330/33534e6c-25e7-11e7-8c9d-7d684d0819a6.png)

![image](https://cloud.githubusercontent.com/assets/26605197/25255347/534faeae-25e7-11e7-8431-97cb6a937992.png)

**Comment by rburkey87** [comment]
@Aleniras - do we need to bother with the two search issues if we're removing the search bar while the mobile menu is opened?

I've already made some of the other changes - just going over them with Katria before pushing to the server.

**Comment by Aleniras** [comment]
Yes  - both search issues still need to be addressed because they are problematic even when the menu is not expanded.  Thanks for checking.

**Comment by Aleniras** [comment]
Looks like the search icon is having trouble in firefox

![image](https://cloud.githubusercontent.com/assets/26605197/25448578/21b01db4-2a76-11e7-97fb-cf023420cbe3.png)

**Comment by ThatJoeMoore** [comment]
Fixed in #175
