### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#165]
# One-Line Summary

The README.md links to theme.byu.edu which is an unfinished site. We could replace that link with the components link.

# Websites Affected

theme.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x ] A request for a new feature/enhancement?

# Detailed Description

The README.md links to theme.byu.edu which is an unfinished site. We could replace that link with the components link. It serves the purpose that the theme site is said to serve.

**Comment by kebowdog** [comment]
Fixed in #200
