### ISSUE TITLE
Drupal Blocks don't appear in Left Sidebar region.

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#167]
# One-Line Summary

Blocks place in the Left Sidebar region on the Drupal components theme don't appear, but they do if they're place in a different region.

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
[https://sandbox.blaketmorgan.com/drupal/home](url)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Apple Safari
- [x ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*

I created a custom view/block, but when I put it in the left sidebar region, it doesn't display (though it does appear in the HTML). When I try a core block, those also don't display. I have tested putting them in different regions and they display.

**If the issue is with styling, please include screenshots!**

![left-sidebar-error](https://cloud.githubusercontent.com/assets/9389424/25443241/7aa8bffa-2a64-11e7-83c1-79856352dc2a.png)

**Comment by katrialesser** [comment]
This wasn't an issue with the theme; it was an issue with his block setup. Closing.
