### ISSUE TITLE
[FEATURE] Allow for configurable max width on the header and footer.

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#173]
# One-Line Summary
We need to have an attribute like constrained-width="1000px" that can be set on the header and on the footer ( i think), and if that is set, we use that setting instead of the default 1200px.

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

**Comment by ThatJoeMoore** [comment]
I propose the attribute name `max-width` - it matches the CSS property, which is nice. Also, we could even use it to get rid of the `full-width` attribute (though we need to keep using that, since it's there and we need to keep backwards-compatibility).  You could specify `max-width="100vw"` to get the same effect as `full-width`.

**Comment by kebowdog** [comment]
In today's meeting we decided to address this after we resolved the footer problems described in issue #210.
