### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#177]
Can we build in the favicon as part of the components?

Should be this:
![image](https://cloud.githubusercontent.com/assets/26605197/25865293/aca66016-34af-11e7-953d-4358003c274a.png)

**Comment by ThatJoeMoore** [comment]
It's not possible to do that with web components. We should, however, host
the favicon on the CDN (I'm already putting together a bundle of common
images and icons), and document how to include it in our documentation.

**Comment by ThatJoeMoore** [comment]
We can (and should) also have the Drupal and Wordpress themes use that favicon.

**Comment by bmorgan296** [comment]
In #165 we added information about the favicon into the read for the components repo and added the favicon to the byu-assets repo.
