### ISSUE TITLE
Footer not full-width in non-chrome browsers

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#178]
# One-Line Summary

In Firefox, Edge, and IE11

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type
styling issue

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [x] Asp.NET
- [ ] Don't Know

# Detailed Description
The footer appears to be left-aligning rather than expanding to fill the 1200px width in non-chrome browsers. It doesn't look too terrible, but it is inconsistent.

**If the issue is with styling, please include screenshots!**

Here's what it looks like in Chrome:
![image](https://cloud.githubusercontent.com/assets/19493582/25872543/6a811faa-34c8-11e7-9735-3f069e4035ca.png)

Here it is in Edge/Firefox:

![image](https://cloud.githubusercontent.com/assets/19493582/25872573/8528e31a-34c8-11e7-8c79-de08299c69e0.png)

**Comment by rburkey87** [comment]
Works fine in Safari too.

**Comment by ThatJoeMoore** [comment]
I'm pretty sure I just fixed this with #183
