### ISSUE TITLE
Empty `byu-footer` has grey bar above it in polyfilled browsers

### ISSUE THREAD

**Issue by klew91** [byuweb/byu-theme-components#182]
# One-Line Summary
Tested on iPhone 6, the byu footer has a section of gray margin above it. Does not show up on desktop, only on phone

# Websites Affected
dev.science.cpms.byu.edu (this is a dev server so you won't be able to go to it
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [x] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description
I'm building a site for the College of Physical and Mathematical Sciences. I included the new simple byu footer (just the blue bar with the university name and copyright info), and there is a gray bar that appears above the footer on any browser in iOS on an iPhone 6. Not sure if this is an issue with other devices yet, but at least it is a problem on this one. I included a screenshot from the phone. The problem does not happen on a desktop computer. 
![img_0611](https://cloud.githubusercontent.com/assets/21326895/26020591/7d34c03a-373d-11e7-93af-3b5376255822.PNG)

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

**Comment by ThatJoeMoore** [comment]
@klew91 Since we can't access the site that's having the problem, could you post the markup for the footer? I've got a theory as to what it might be (an empty `<byu-footer-column>` or `<div>` inside the `<byu-footer>`, but I haven't yet explained why it only shows up on mobile for you.

**Comment by klew91** [comment]
All I did was use the <byu-footer></byu-footer> html. That's it.

**Comment by ThatJoeMoore** [comment]
Interesting. Where on campus is your office? Would you mind if I stopped by sometime next week to take a look at this with you?

**Comment by klew91** [comment]
N-181 Eyring Science Center. What day and time works for you?

**Comment by ThatJoeMoore** [comment]
Would Monday at 10 work for you?

**Comment by klew91** [comment]
Yeah that sounds good. I'll see you then!

**Comment by klew91** [comment]
Joseph,

As it turns out, I'm not going to be able to be at the office at 10 this
morning. Is there a time this afternoon that works for you? I apologize for
the inconvenience!

**Comment by ThatJoeMoore** [comment]
Does 2 work?

**Comment by klew91** [comment]
Yes that's better for me. Thanks!

**Comment by ThatJoeMoore** [comment]
@klew91 I never actually got you name, which might help me find where you're at in the office ;)

**Comment by klew91** [comment]
Sorry about that, it's Kevin Lew. When you come in, ask for me and i'll
come meet you

**Comment by ThatJoeMoore** [comment]
Digging into this with @klew91 , it looks like this is actually a problem with all polyfilled browsers, even on desktop.  I think it got introduced in [faf4bc7](https://github.com/byuweb/byu-theme-components/commit/faf4bc7ad33558fbb663fea21eb9e018e821f2f7), but I'm not sure.  Regardless, I'm going to work on finding a better solution to padding the top and bottom of the secondary footer.

**Comment by ThatJoeMoore** [comment]
Digging in, it looks like what's happening here is that we've got a bunch of styles that have the ::slotted pseudo-element that are applied to the secondary-footer element:

```
.secondary-footer ::slotted(*) {
    /* stuff */
}
```

This causes problems when in browsers using the polyfills/ShadyDOM.  It needs to be this:

```
.secondary-footer-content ::slotted(*) {
    /* stuff */
}
```

I'll have a PR with this fix shortly.

**Comment by ThatJoeMoore** [comment]
@klew91 If you want to test the fix, you can change your script source to `https://cdn.byu.edu/byu-theme-components/experimental/issue-182/byu-theme-components.min.js` (it swaps out `latest` for `experimental/issue-182`).

**Comment by klew91** [comment]
Joseph,

I tested the fix. Now the footer is completely gone. This is true for both
Chrome and Firefox.

**Comment by rburkey87** [comment]
Is the blue bar portion of the footer gone also?

It's working fine on my test pages. The only time it adds the grey bar is when I have the `<byu-footer-column>` component in my html, but with no content added. If you only have the `<byu-footer>` component, you should only see the blue footer bar.

**Comment by klew91** [comment]
Yes, the blue bar part of the footer is also gone. There is no footer at
all. I made no change to the component. I still only have
<byu-footer></byu-footer>

**Comment by ThatJoeMoore** [comment]
Yeah, that's because I gave you a URL that doesn't work.  Try `https://cdn.byu.edu/byu-theme-components/unstable/byu-theme-components.min.js`

**Comment by klew91** [comment]
Ok, tested with the unstable branch, the problem is fixed. I checked on
Chrome and Firefox on Desktop and Chrome on iOS and the gray bar is gone.
