### ISSUE TITLE
No search icon in non-Chrome/Safari browsers (Drupal)

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#185]
# One-Line Summary
Search icon not appearing in button on non-Chrome browsers (Drupal only).

# Websites Affected

https://calendar.byu.edu/
https://theme-dev.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
Search icon not appearing in button in Firefox, Edge, and IE11 (Drupal only).

**If the issue is with styling, please include screenshots!**
![image](https://cloud.githubusercontent.com/assets/25965299/26118951/d783997e-3a28-11e7-8630-39cca755afed.png)
![image](https://cloud.githubusercontent.com/assets/25965299/26118958/dde5c2b0-3a28-11e7-81a7-37b0d0ac9899.png)

**Comment by katrialesser** [comment]
Found a little theme code in Zurb to override, all fixed in the Drupal theme.
