### ISSUE TITLE
Left-align attribute

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#186]
# One-Line Summary
Menu items do not align properly when left-align attribute is active.

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

http://beta.mentoring.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site (HTML)
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
When left-align attribute is applied (should be active when less menu items are present):
- does not apply in Firefox/Edge (HTML/Drupal); menu links are stretching across full width of page
Edge:
![image](https://cloud.githubusercontent.com/assets/25965299/26119064/3fc8b49c-3a29-11e7-92fe-5d48aed465a0.png)
![image](https://cloud.githubusercontent.com/assets/25965299/26119265/e8808b6e-3a29-11e7-8387-43b99dbf1c27.png)
Firefox:
IE11:
![image](https://cloud.githubusercontent.com/assets/25965299/26119387/423c56a6-3a2a-11e7-979e-539a0386e064.png)

- menu items add additional padding within mobile menu (Edge Drupal/HTML)
Edge:
![image](https://cloud.githubusercontent.com/assets/25965299/26119179/9d3f4140-3a29-11e7-823f-1b5247918a46.png)
![image](https://cloud.githubusercontent.com/assets/25965299/26119230/cb8f4824-3a29-11e7-8904-086e67ef2321.png)
Firefox:
![image](https://cloud.githubusercontent.com/assets/25965299/26119342/1e9794b8-3a2a-11e7-9b4a-fe268292959e.png)
IE11:
![image](https://cloud.githubusercontent.com/assets/25965299/26119404/54f82464-3a2a-11e7-9916-cadfaaf6a3b2.png)

**Comment by ThatJoeMoore** [comment]
Also reported on Slack.  You can use http://beta.mentoring.byu.edu/ to test.
