### ISSUE TITLE
"Brigham Young University" SVG is black in IE11

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#187]
# One-Line Summary
"Brigham Young University" SVG is black in IE11

# Websites Affected

https://theme-dev.byu.edu/
[components not loading on BYU Calendar in IE11]

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site (HTML)
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
"Brigham Young University" SVG in the blue footer bar is black (instead of white) in IE11.

**If the issue is with styling, please include screenshots!**
![image](https://cloud.githubusercontent.com/assets/25965299/26119647/342a0f8a-3a2b-11e7-99f1-a7931bfc6cdd.png)
![image](https://cloud.githubusercontent.com/assets/25965299/26119660/3cfa76e0-3a2b-11e7-8bc8-34bf7ea233eb.png)

**Comment by ThatJoeMoore** [comment]
This is because that image is using an SVG feature that IE11 doesn't support.  We have to change from using the `style` tag to color the image to using `fill="#FFFFFF` on each path (like the header monogram logo uses).
