### ISSUE TITLE
Phone number in footer has an underline (Edge only)

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#188]
# One-Line Summary
Phone number in footer has an underline (Edge only)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site (HTML)
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
Phone number in footer has an underline (Edge only)

**If the issue is with styling, please include screenshots!**
![image](https://cloud.githubusercontent.com/assets/25965299/26119763/ab602a26-3a2b-11e7-93cf-be2b94e4012d.png)

**Comment by kebowdog** [comment]
Fixed by PR #197

**Comment by ThatJoeMoore** [comment]
@kebowdog Are you sure I fixed this?  I didn't intentionally do it.  If I did it, I must just be THAT awesome!

**Comment by kebowdog** [comment]
Good catch, I didn't look closely enough at the issue. Reopening....

**Comment by kebowdog** [comment]
Ok, after looking more closely at this, the issue appears unrelated to the components, and is a "feature" unique to Microsoft Edge: https://stackoverflow.com/questions/31978346/remove-microsoft-edges-phone-number-styling 

The suggested workaround is to replace phone numbers with tel links:
<a href="tel:888-888-8888">(888) 888-8888</a>

or else disable Edge's automatic detection of phone numbers (which I wouldn't recommend). Since this is an Edge issue and not a components issue I'll go ahead and close it.

**Comment by ThatJoeMoore** [comment]
I agree. I'd be loathe to override a behavior that the users of a specific browser expect to see.
