### ISSUE TITLE
Mobile Menu padding varies in iOS mobile browsers

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#190]
# One-Line Summary
Mobile Menu padding varies in iOS mobile browsers

# Websites Affected

BYU Calendar not updated to show issue

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site (HTML)
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
Drupal Constrained-Width (no padding issues):
![image](https://cloud.githubusercontent.com/assets/25965299/26120111/e1f28a92-3a2c-11e7-9bad-916bf3588617.png)
Drupal Full-Width (no padding):
![image](https://cloud.githubusercontent.com/assets/25965299/26119919/410e4f12-3a2c-11e7-92be-11bc79d58923.png)
HTML Constrained-Width (only issues with "very long title" link):
![image](https://cloud.githubusercontent.com/assets/25965299/26119923/44841186-3a2c-11e7-9b48-bd8464f38587.png)
HTML Full-Width (no padding):
![image](https://cloud.githubusercontent.com/assets/25965299/26119929/4a20bba8-3a2c-11e7-99c6-fd21ee833f50.png)

**Comment by bmorgan296** [comment]
This also is appearing on websites that do not have full-width toggled on. An example is [auc-dev.byu.edu](url).
