### ISSUE TITLE
Dropdown menu container margin fixed size

### ISSUE THREAD

**Issue by arzon94** [byuweb/byu-theme-components#192]
# One-Line Summary
The slot-container div has left:0 and right:0 attributes limiting the background to a fixed space smaller than text

# Websites Affected
map.byu.edu (currently the byu-theme-conversion branch on github)

# Issue Type

- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

all

# Web Site Platform

*What is hosting your website?*

.net mvc

# Detailed Description

remove the left:0 css style

![image](https://cloud.githubusercontent.com/assets/16659722/26327495/ebb42d22-3efc-11e7-8191-b45634b66b5a.png)

**Comment by ThatJoeMoore** [comment]
AFAIK, the spec dictates that the right side of the dropdown should align with the right side of the space in the nav bar, which is the only way to make it work properly in some of the cases we run into.  Thus, the `right: 0` is correct, and the `left: 0` should be removed.

**Comment by ThatJoeMoore** [comment]
Looking at the behavior for this case on 2017-core-components-demo.cdn.byu.edu, I think that the `left: 0` was intentionally put there to satisfy design requirements.  It makes it so that the dropdown is the same size as the `More` element above it. The text is then set to truncate with an ellipsis.  This works great in many situations, but it looks like this site has narrow nav bar elements and long links in the more menu.  

@Aleniras, is it part of the spec that the more dropdown be the same width as the button?  Perhaps we should have it match that width *at a minimum*, but expand to the left in order to accommodate longer links?

So, if we made it expand to the left, it would look more like this:

![screen shot 2017-05-22 at 3 20 33 pm](https://cloud.githubusercontent.com/assets/455981/26328942/4317288a-3f02-11e7-996b-30c1632eb11a.png)

**Comment by ThatJoeMoore** [comment]
@arzon94 Pending feedback from our designer, you can test my solution for this by replacing the `latest` in your script tag URL with `experimental/issue-192`.

So, it would look like this:

```
<link rel="stylesheet" href="https://cdn.byu.edu/byu-theme-components/experimental/issue-192/byu-theme-components.min.css">
<script async src="https://cdn.byu.edu/byu-theme-components/experimental/issue-192/byu-theme-components.min.js"></script>
```

Those links will remain valid until we close the issue, at which time you'll want to point back to `latest`.

**Comment by arzon94** [comment]
Works well for the extra long links

**Comment by Aleniras** [comment]
@ThatJoeMoore I think your solution is great. We don't want it overly long if there are short links, but it's okay to increase the width more than the "MORE" button.  Can we put in a max character width on here with ellipses to avoid problem scenarios?

**Comment by Aleniras** [comment]
@ThatJoeMoore How about at 30 for the max character width.

**Comment by ThatJoeMoore** [comment]
A max pixel width would be better, since characters have different widths ;)

**Comment by ThatJoeMoore** [comment]
@Aleniras how does 250px sound?

![screen shot 2017-05-22 at 4 26 03 pm](https://cloud.githubusercontent.com/assets/455981/26330888/67168a24-3f0b-11e7-8eb5-2a4ad64a7b8f.png)

And here's what 300px looks like:

![screen shot 2017-05-22 at 4 27 08 pm](https://cloud.githubusercontent.com/assets/455981/26330926/91d7effa-3f0b-11e7-9f40-8b804ad5c7e9.png)

**Comment by Aleniras** [comment]
@ThatJoeMoore Let's do 250. Thanks!

**Comment by arzon94** [comment]
![image](https://cloud.githubusercontent.com/assets/16659722/26367344/76b37974-3fab-11e7-9dfd-910c81ad53c9.png)
The dropdown is not creating the ... and just barely crosses the background. It also has a larger margin than pictured in above pictures. Can the length be changed to 275 or the margin be changed for dropdown items?

**Comment by ThatJoeMoore** [comment]
By default, there isn't as large of a margin being applied on the links (look at the images I've posted). I bet if you take off the margins or padding on your links, it'll work better. That's probably throwing off the sizing and overflow settings.
