### ISSUE TITLE
Descending letters in the Site name get cut off.

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#204]
# One-Line Summary

Descending letters in the Site name get cut off. 

# Websites Affected
theme-dev.byu.edu  - the p in Developer Guide
Testing sites.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
https://theme-dev.byu.edu/
I can't share my local D8 version (working on a D8 theme) but it's the same everywhere that I've seen.

# Issue Type
Slight css issue
*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Apple Safari
- [X] Microsoft Edge
- [] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [X] Drupal 7
- [X] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
![image](https://cloud.githubusercontent.com/assets/12898896/26473617/bfc697e4-4169-11e7-8b3f-b559c78f073a.png)
![image](https://cloud.githubusercontent.com/assets/12898896/26473673/1b2f489c-416a-11e7-9aa0-8dc141796a37.png)

**Comment by kebowdog** [comment]
@katrialesser This appears to be a conflict with the default CSS from your Drupal template. Specifically, you have a line-height: 1 applied to the body tag, and if we remove that the styles display normally. However, this is likely to be a common problem, so I'd recommend we add a line-height: initial; or something similar to the byu-header-title to override this from the component side. I'll submit a PR.

**Comment by bmorgan296** [comment]
Fix in PR #207

**Comment by bmorgan296** [comment]
Fixed in #207

**Comment by katrialesser** [comment]
I just confirmed that this is fixed - for site title, subtitle after and subtitle before.
