### ISSUE TITLE
Add Sitemap Link in Footer

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#205]
# One-Line Summary
Add site map theme in footer.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [x] Drupal 8
- [x] Wordpress
- [x] Custom Site
- [ ] Don't Know

# Detailed Description

Add a slot in the blue footer that can link to a sitemap.

**Comment by ThatJoeMoore** [comment]
As far as I know, there is no allowance for this in the design spec. That's what the customizable footer space is for. @Aleniras can correct me if I'm wrong about the spec, but we're very consciously not allowing customization of the top and bottom blue bars beyond some very specific pieces. The content in the middle is where such customization can and should happen.

**Comment by Aleniras** [comment]
@bmorgan296 Can you send a screenshot of what you were envisioning? We have places for a "directions" link, but let me know if that isn't sufficient.

**Comment by Aleniras** [comment]
Yes to this ^.  Let us know if the "directions" link in the footer doesn't meet your needs and we can revisit.

**Comment by bmorgan296** [comment]
I got the idea from the bootstrap thing, but if we consciously left that out, that makes total since. This is what it looks like in the bootstrap theme: 
![capture](https://cloud.githubusercontent.com/assets/9389424/26592288/97a439ee-451d-11e7-94da-437b1681c75f.PNG)

**Comment by Aleniras** [comment]
@robertwcook Could you eliminate "site map" from the copyright line so that it matches everything else please?

**Comment by bmorgan296** [comment]
No sitemap is intentional. If consumers want it, they can use the gray footer.

**Comment by robertwcook** [comment]
@Aleniras the additional link often see as 'Site Map' is an option of the Bootstrap theme. Not required. We've had a use case where the area footer is overkill for a single additional footer link. ¯\_(ツ)_/¯ Happy to look at how it's being used an encourage different use if needed.

**Comment by Aleniras** [comment]
Great. Thanks!
