### ISSUE TITLE
No Search Button in IE11

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#208]
# One-Line Summary
No search button appears in IE11.

# Websites Affected
asb-ucom-dev1.byu.edu
asb-ucom-dev2.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

# Detailed Description

The search button isn't showing in IE11. It isn't even loaded in the HTML.
![capture](https://cloud.githubusercontent.com/assets/9389424/26594098/a44382ee-4523-11e7-87f4-a15da63d0a25.PNG)

**If the issue is with styling, please include screenshots!**

**Comment by rburkey87** [comment]
If it's built in Drupal7, make sure you've done a git pull on the theme to download the latest updates. I'm seeing this problem in my HTML builds, but not the Drupal sites.

**Comment by bmorgan296** [comment]
This issue will be revisited after implementing refactoring the search as explained in #219.

**Comment by ThatJoeMoore** [comment]
Yeah, I can't duplicate this issue.  I'm trying in IE11 and Edge on Windows 10, and the pages listed appear to render properly. @bmorgan296 Can you confirm?

**Comment by bmorgan296** [comment]
LGTM
