### ISSUE TITLE
[BYU-HEADER] Header calculated width > 1200px

### ISSUE THREAD

**Issue by GardinerMatt** [byuweb/byu-theme-components#220]
# Description

*Tell us all about your problem or feature proposal.*
byu-header is 1232 pixels wide instead of 1200px wide because it has margins of 16px on either side.  box-sizing doesn't consider margins.

**If the issue is with styling, please include screenshots!**
To work around this padding has to be added to the .page-content section so that its content lines up with the header text.  For a full page site, that means that you have to set the max-width: of .page-content to 1232 to make everything look normal (assuming you're using the margin:0 auto method of centering .page-content).

(with no padding)
![screen shot 2017-05-31 at 9 23 45 am](https://cloud.githubusercontent.com/assets/19825047/26639846/28e407ca-45e3-11e7-8529-b72dabeda873.png)

(with padding @ > 1200px)
![screen shot 2017-05-31 at 9 24 24 am](https://cloud.githubusercontent.com/assets/19825047/26639862/39122258-45e3-11e7-9515-3f8497fbe24b.png)

(with padding and .page-content max-size set to 1232px)
![screen shot 2017-05-31 at 9 27 20 am](https://cloud.githubusercontent.com/assets/19825047/26639927/67562402-45e3-11e7-9fdb-a3109bf78400.png)
![screen shot 2017-05-31 at 9 27 28 am](https://cloud.githubusercontent.com/assets/19825047/26639932/6c5b824e-45e3-11e7-9db1-c2128a1b4e69.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
The components only take care of the header, menu, and footer of a site. Since this is in the main content section of the site, it is out of our control. The issue here is with our documentation. I will update the suggested `.page-content` style.

**Comment by kebowdog** [comment]
Actually I think a better solution would be to apply the correct box-sizing style to the header so that the header actually does have a width of 1200px. This will be especially important once we implement the ability to set a custom width for the header and footer.

**Comment by bmorgan296** [comment]
Sounds good. Can you take care of this one then, @kebowdog? I have already created a branch for it. issue-220-header-width.

**Comment by GardinerMatt** [comment]
@bmorgan296 I agree with that.  I originally mentioned this on Slack as a documentation issue but was asked to create a bug report.  @kebowdog there is no box-sizing model that takes margin into account.  Margin is a buffer outside of the box.  You'll have to put the spacing fix inside the box by using padding or some other method.

**Comment by ThatJoeMoore** [comment]
I asked @GardinerMatt to create this issue.  The design spec says that the header is 1200px, so it should be 1200px instead of 1232.  I'm certain that we can change the margins to padding, then use `box-sizing: border-box;` in order to make it actually be 1200px.

If we say it's 1200px, it should actually be 1200px.

**Comment by kebowdog** [comment]
I've gone around and around on this one, and I have a few ideas on how to handle this. I'd like to get the group's input at today's meeting.
