### ISSUE TITLE
[byu-menu] Menu is calculating counts for 'More' menu and 'left-align' attribute wrong

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#224]
# Description

Reported by @dbluhm

The calculation of the count for the 'More' menu and the 'left-align' attribute is flawed.  It uses `this.children` to get the list of child components, which is flawed (especially in Shady DOM).  It should be getting a reference to the menu slot, then calling `assignedNodes()` on it, then filter the result by those where `node instanceof HTMLElement` is true.  This will ensure that we're actually seeing the slotted elements, and not other elements/nodes.  This is especially important in browsers using Shady DOM (like Firefox), since `this.children` will return the root elements of the Shadow DOM template, NOT the Light DOM children, since those have already been rearranged and moved to their proper locations in the DOM.

# Websites Affected

https://web3.fsl.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

All

**Comment by kebowdog** [comment]
I actually had to fix this while I was working on issue #220. If you're ok letting me take over it this should be addressed in my next PR.

**Comment by ThatJoeMoore** [comment]
Sounds good.
