### ISSUE TITLE
[BYU-FOOTER] Text wraps @ < 400 CSS pixels

### ISSUE THREAD

**Issue by GardinerMatt** [byuweb/byu-theme-components#225]
# Description

*Tell us all about your problem or feature proposal.*

There is so much text in the contact area of the footer, that it wraps on phones with a css pixel width of < 400 (iPhone 6, Galaxy S7, LG G6, etc).  This combined with the line-height of the footer makes it so that the text doesn't fit in the footer area in an attractive way.  

**If the issue is with styling, please include screenshots!**
![screen shot 2017-06-02 at 2 10 19 pm](https://cloud.githubusercontent.com/assets/19825047/26743138/fa9f5718-479d-11e7-966e-794f2601f5d4.png)
![capture _2017-06-02-14-09-07](https://cloud.githubusercontent.com/assets/19825047/26743146/02d2e472-479e-11e7-91e3-a09ff6167345.png)

# Websites Affected
All websites using web components

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

https://saasta-dev.byu.edu/noauth/registrar/challengeexams/ (WIP)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
All?

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
@Aleniras, we looked at this in our meeting today and our proposed solution is just to make the footer taller on smaller screens. Does that sound good to you?

**Comment by GardinerMatt** [comment]
This is actually my fault.  You're not setting a line-height on the footer like I thought you were, so my css bleeding into the footer and creating that huge text gap.  There is still the issue of the phone number breaking on the hyphen but that is not as big of a deal to me.

**Comment by kebowdog** [comment]
Makes sense. In that case I'll just add a tweak so it doesn't break in the middle of the phone number.

**Comment by Aleniras** [comment]
@kebowdog what size do you have the font at at the smallest point? Also, if you're going to put it onto two lines, can you make the line height 1 pt larger than the font size please?
