### ISSUE TITLE
Site Title should be centered vertically in the same way "username" and "signout" are.

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#226]
![image](https://cloud.githubusercontent.com/assets/26605197/26744713/55a5568e-47a4-11e7-8b0b-260b4352c6c6.png)

**Comment by ThatJoeMoore** [comment]
They actually are.  It's the different fonts and font sizes that make them appear not to be, but if you look closely, the centerlines of the two fonts are in the same place:

![screen shot 2017-06-02 at 3 16 35 pm](https://cloud.githubusercontent.com/assets/455981/26745188/a1d67f72-47a6-11e7-9c9b-27b39d3cd453.png)

The world of web typography is a terrible, terrible place.

**Comment by kebowdog** [comment]
Since this appears to be a non-issue I'm going to close it. @Aleniras, there are other options for how to vertically position these fonts (for instance we could give them the same baseline, though I wouldn't recommend that) so if you'd like to explore those let us know.
