### ISSUE TITLE
byu-header long-link styling off on smaller screen sizes

### ISSUE THREAD

**Issue by dbluhm** [byuweb/byu-theme-components#237]
# Description
Long links don't expand to fill the screen when the drop down menu is used for smaller screens.

Images for reference:
![long-link-error](https://user-images.githubusercontent.com/22032832/26902495-bd2ccab2-4b96-11e7-917a-cccee68ffc52.png)
The menu item shown here is a "long-link"

![long-link-error-reference](https://user-images.githubusercontent.com/22032832/26902517-cf87d8a0-4b96-11e7-8aa5-c62efccd3ce9.png)
The menu item here is not.

# Websites Affected
web3.fsl.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by Gi60s** [comment]
Nice catch. I'll fix that one.

**Comment by kebowdog** [comment]
Fixed by #260
