### ISSUE TITLE
Footer Doesn't Stack Properly

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#241]
# Description

The footer doesn't stack completely on some smaller browsers. This is not a bug with the components, rather the doumentation needs to be updated so users know to include the `<meta name="viewport" content="width=device-width, initial-scale=1.0">` tag.
![capture](https://user-images.githubusercontent.com/9389424/27089112-b92cf03e-5016-11e7-9767-8fc0f664034f.PNG)

# Websites Affected

[asb-ucom-dev1.byu.edu](//asb-ucom-dev1.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Just checked it myself - it's definitely caused by not including the viewport meta tag, so we can definitely add that to the documentation. Also, just a note that the test site you referenced isn't implementing the "sticky footer", which is something I'd recommend so you don't have a strange empty white area at the bottom of your page.
