### ISSUE TITLE
Close mobile menu upon clicking link

### ISSUE THREAD

**Issue by arzon94** [byuweb/byu-theme-components#244]
# Description
Upon clicking a link, the mobile menu should collapse to display the page
*Tell us all about your problem or feature proposal.*
Doing some dummy-testing with my wife on the map-dev.byu.edu site, she could not for the life of her figure out how to get back to the map. She expected to automatically see the results on the map after clicking. Generally there is no need to collapse the menu because a link redirects to a new page, but collapsing the menu is useful in a mobile browser if you are staying on the same page.
**If the issue is with styling, please include screenshots!**

# Websites Affected
map-dev.byu.edu
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

![image](https://user-images.githubusercontent.com/16659722/27157825-d60924c4-5120-11e7-8975-b1be43d1778c.png)

**Comment by devingd** [comment]
I'm writing a site in Angular 2 and just barely ran into this issue, too.

**Comment by ThatJoeMoore** [comment]
Great catch.  I hadn't had a chance to test this in a single-page app.

Now that I'm thinking about it, I bet this is also a problem with the more menu dropdown on desktop.

**Comment by arzon94** [comment]
Tis on desktop as well, although for the map site on desktop I like it, because I can select as many categories to display as I want without the menu collapsing. But then again maybe the majority of people don't care to select more than one category? More of a UX question beyond me.

**Comment by ThatJoeMoore** [comment]
Hmm.  That's an interesting use case, then, if you're allowing people to
select things from the nav bar. If we do this, we'll also want to add an
attribute to disable it, so that use cases like yours can be made to work.

**Comment by Gi60s** [comment]
Via discussion in today's engineering meeting, the more menu should collapse by default in both mobile and non mobile mode. Alternatively there is an attribute that can be set to keep it open.

**Comment by kebowdog** [comment]
fixed in #256
