### ISSUE TITLE
[BYU-MENU] More Arrow Animation

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#250]
# Description

*Tell us all about your problem or feature proposal.*
From @Aleniras: When the more menu is expanded, the arrow is above center. Also, because it is pointing up, it is pointing opposite of where we want the user to focus.
**If the issue is with styling, please include screenshots!**
<img width="281" alt="screen shot 2017-06-20 at 3 51 48 pm" src="https://user-images.githubusercontent.com/9389424/27357659-65bcc0c2-55d0-11e7-926e-7d00563b1db7.png">

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
[map.byu.edu](http://map.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Fixed in #257 and #258
