### ISSUE TITLE
byu-footer multiple headers within byu-footer-column

### ISSUE THREAD

**Issue by dbluhm** [byuweb/byu-theme-components#253]
# Description
It would be nice to be able to have multiple headers (or maybe you could think of it as multiple sub-sections within a single column) within a byu-footer-column.

# Websites Affected

https://web3.fsl.byu.edu (In the footer column that has "Notices" and "Calendar")

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Web Site Platform

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
We discussed this in our Engineering group meeting and I believe @aleniras was planning to respond to this.

**Comment by Aleniras** [comment]
Thanks for the reminder.
@dbluhm We'd like to encourage best practices here, so we're going to keep with the four-column headers for the main components. The problem with enabling duplicate headers within the same column is that it increases confusion with hierarchy, and also encourages less consistency from site to site in the header and footer. Let me know if you'd like to talk through this more and we can set up a time to meet!

**Comment by kebowdog** [comment]
I'll go ahead and close this for now and we can reopen if needed.

**Comment by dbluhm** [comment]
@Aleniras Thanks for the response and considering the idea.
