### ISSUE TITLE
[FEATURE] Podcast icon option in the footer

### ISSUE THREAD

**Issue by Gi60s** [byuweb/byu-theme-components#254]
# Description

*Tell us all about your problem or feature proposal.*

Request from Dylan Moh from slack: "Hey guys, I'm with Publications and Graphics and have been working with the components. Would it be possible to include a podcast icon along with the other icons?"

Approved by Aleni on June 27 at 9:56 AM in #engineering-group channel.

**Comment by ThatJoeMoore** [comment]
Here's the icon Aleni wants us to use: https://cdn.byu.edu/shared-icons/latest/social/obfuscated/po.svg .  We're supposed to make it purple, but I don't have a specific color yet.
