### ISSUE TITLE
Menu background

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#261]
# Description
Menu bar background doesn't extend beyond menu items (uses body color by default) when page width is constrained.

We need to add `background-color: #fff` directly to `.menu-outer-wrapper` and set the transparency class to that instead of `byu-menu` (no double-transparency occurs if it's applied in both places). Here's a screenshot of what I'm showing when I place a hero image behind the menu with the menu transparent.

![image](https://user-images.githubusercontent.com/25965299/27887254-08511450-619d-11e7-99f8-dd3865a895a4.png)

# Websites Affected
https://theme-dev.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
I'm seeing this too. Like you mentioned, it happens on any page with a non-white body background color. One example is https://hs.byu.edu/About.
