### ISSUE TITLE
[BYU-HEADER] home-url attribute launches new tab/window

### ISSUE THREAD

**Issue by GardinerMatt** [byuweb/byu-theme-components#265]
# Description

*Tell us all about your problem or feature proposal.*
If you set the home-url attribute on the byu-header then a click on the BYU logo causes the URL specified in home-url to launch in a new window/tab.  This is not the typical behavior for clicking on a logo.

**If the issue is with styling, please include screenshots!**

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
https://saasta-dev.byu.edu/noauth/registrar/challengeexams/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ x] Google Chrome
- [ x] Mozilla Firefox
- [ x] Apple Safari
- [ x] Microsoft Edge
- [ x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x ] Any browser on iOS
- [x ] Chrome for Android
- [x ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x ] Custom Site
- [ ] Don't Know

**Comment by GardinerMatt** [comment]
Removing target="_blank" from the html for <a id="home-url"></a> should fix this.  It looks like it was added intentionally.  Am I misunderstanding the rationale for that?

**Comment by bmorgan296** [comment]
Nope. I will fix that. Thanks!
