### ISSUE TITLE
[BYU-SOCIAL-MEDIA-ICONS] Right edge of image clipped in Edge.

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#267]
# Description

*Tell us all about your problem or feature proposal.*
The right side of the social media icons is clipped off a little bit, but only in Edge.
![capture](https://user-images.githubusercontent.com/9389424/28087085-7e3342b0-663e-11e7-971d-a6258d4beb2c.PNG)

# Websites Affected
[asb-ucom-dev1.byu.edu](http://asb-ucom-dev1.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
This appears to be a problem with the icons themselves.  I'll push a fix in byuweb/shared-icons .

**Comment by ThatJoeMoore** [comment]
I've fixed this, and the fix should be rolling out across all sites as soon as the CDN finishes its build.
