### ISSUE TITLE
Footer link font size

### ISSUE THREAD

**Issue by matalyn2** [byuweb/byu-theme-components#272]
# Description

*Tell us all about your problem or feature proposal.*
I was chatting with Aleni, and she mentioned that the footer text is just under the design size. I've attached the specs she sent me about their sizing. 

**If the issue is with styling, please include screenshots!**
<img width="479" alt="screen shot 2017-07-14 at 12 30 43 pm" src="https://user-images.githubusercontent.com/19268962/28225906-6c302506-6891-11e7-8dbe-f900aebc0e79.png">

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
https://president.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [x] Wordpress
- [ ] Custom Site
- [x] Don't Know

**Comment by bmorgan296** [comment]
So to clarify: currently the footer text doesn't meet those specs and they need to be changed?

**Comment by matalyn2** [comment]
That is correct, it looks like it is just under.

**Comment by bmorgan296** [comment]
@matalyn2 or @Aleniras: What does it mean by Gotham Book?

**Comment by kebowdog** [comment]
It looks like @bmorgan296 added the font-size and color in #279. Can someone confirm so we can close this?

**Comment by bmorgan296** [comment]
We will need to revisit changing the fonts because that will cause re-flow of the text which could cause problems.

**Comment by ThatJoeMoore** [comment]
I'm going to close this.  It seems like there are two conversations here: what the font size should be and what the hover style should be.  The font size issue is fixed in #279.  If there's a problem with the hover styles, let's address that separately.
