### ISSUE TITLE
BYU Header Link

### ISSUE THREAD

**Issue by matalyn2** [byuweb/byu-theme-components#273]
# Description

*Tell us all about your problem or feature proposal.*
The BYU in the header should link to the the host site url, not to byu.edu.

**If the issue is with styling, please include screenshots!**

# Websites Affected
president.byu.edu
brand.byu.edu

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [x] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
By default, that logo will link to the BYU homepage. We decided that in #142. We can revisit this topic in our next engineering meeting. Because that feature of the component was added, Drupal and WordPress theme maintainers should update accordingly. 

Since we'll need to discuss this at our next engineering meeting, I'm assigning this to the next release after WebFest.

**Comment by matalyn2** [comment]
Gotcha! I must have been out for that meeting. I will adjust the wordpress theme accordingly.

**Comment by kebowdog** [comment]
Elaborating on @bmorgan296's comment, by default the BYU logo will link to the BYU home page, though this can be overridden by adding a "home-url" attribute to the byu-header component (see the second demo on this page: http://2017-components-demo.cdn.byu.edu/byu-header.html). I'm going to go ahead and close this issue as a duplicate.
