### ISSUE TITLE
Main index.html issue

### ISSUE THREAD

**Issue by Adenn** [byuweb/byu-theme-components#274]
# Description

When you try and open the index.html file in the root of the components folder it is set to just redirect.  However, the redirect doesn't work as it tries to go to c:\docs\ which generally doesn't exist.

I modified line 13 to look like this:

window.location.href = "./docs/index.html";

This resolves the issue and opens the primary docs index file.

# Websites Affected

Documentation issue, doesn't affect live site.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ x] Google Chrome
- [ x] Mozilla Firefox
- [ x] Apple Safari
- [ x] Microsoft Edge
- [ x] Microsoft Internet Explorer 11
- [ x] Other (please specify)
 - SHOULD have this issue with all browsers.

## Mobile Browsers

- [x ] Any browser on iOS
- [x ] Chrome for Android
- [x ] Firefox Mobile for Android
- [x ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
Resolved in #278
