### ISSUE TITLE
[byu-footer] Extra Margins with p tag: Edge

### ISSUE THREAD

**Issue by jkenyonc** [byuweb/byu-theme-components#276]
# Description
In edge, text in the BYU footer is formatted incorrectly. It is all indented and the space between p tags is far to big. It only happens in edge. I am using the byu_2017_d7 theme.
![capture-edge](https://user-images.githubusercontent.com/12718528/28230935-0517a5d2-68a6-11e7-8a72-efe274452234.PNG)

**If the issue is with styling, please include screenshots!**

# Websites Affected

theme-dev.byu.edu
(my site is affected but it is not live yet)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [X] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [X] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [X] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
Can you show us you `<byu-footer>` code?

**Comment by jkenyonc** [comment]
`  <byu-footer>
          
      <byu-footer-column>
                  <span slot="header">Contact</span><p>C-205 BNSN<br />
Brigham Young University,<br />
Provo, UT 84664</p>
<p><a href="mailto:kenc@chem.byu.edu">kenc@chem.byu.edu</a></p>
<p>(801) 422-0249</p>
<byu-footer-action-button>
            <a href="https://christensenlab.byu.edu/donate" slot="actiontext">Donate</a>
</byu-footer-action-button>              </byu-footer-column>
      <byu-footer-column>
                  <span slot="header">Helpful Links</span><p><a href="http://snapgene.com">SnapGene</a></p>
<p><a href="http://idtdna.com/pages/scitools">Oligo Analysis Tools</a></p>
<p><a href="http://expasy.org">Bioinformatics Resource Portal</a></p>
              </byu-footer-column>
      <byu-footer-column>
                  <span slot="header">Connect With Us</span><byu-social-media-links>
    
    <a class="facebook" href="https://www.facebook.com/groups/christensenlab/">Facebook</a>
    <a class="linkedin" href="#">Linkedin</a>
    <a class="youtube" href="#">YouTube</a>
</byu-social-media-links>              </byu-footer-column>
      <byu-footer-column>
              </byu-footer-column>
      
      </byu-footer>`

**Comment by jkenyonc** [comment]
<byu-footer>
          
      <byu-footer-column>
                  <span slot="header">Contact</span><p>C-205 BNSN<br />
Brigham Young University,<br />
Provo, UT 84664</p>
<p><a href="mailto:kenc@chem.byu.edu">kenc@chem.byu.edu</a></p>
<p>(801) 422-0249</p>
<byu-footer-action-button>
            <a href="https://christensenlab.byu.edu/donate" slot="actiontext">Donate</a>
</byu-footer-action-button>              </byu-footer-column>
      <byu-footer-column>
                  <span slot="header">Helpful Links</span><p><a href="http://snapgene.com">SnapGene</a></p>
<p><a href="http://idtdna.com/pages/scitools">Oligo Analysis Tools</a></p>
<p><a href="http://expasy.org">Bioinformatics Resource Portal</a></p>
              </byu-footer-column>
      <byu-footer-column>
                  <span slot="header">Connect With Us</span><byu-social-media-links>
    
    <a class="facebook" href="https://www.facebook.com/groups/christensenlab/">Facebook</a>
    <a class="linkedin" href="#">Linkedin</a>
    <a class="youtube" href="#">YouTube</a>
</byu-social-media-links>              </byu-footer-column>
      <byu-footer-column>
              </byu-footer-column>
      
      </byu-footer>

**Comment by bmorgan296** [comment]
That is intentional. `<a>` tags in `<byu-footer-column>` are already formatted to be spaced properly and on new lines, so there is no need to wrap them in `<p>` tags.  We will update the documentation accordingly as well as remove `<p>` tag padding in our v1.1.2 release.

**Comment by ThatJoeMoore** [comment]
His use of <p> tags shouldn't cause an issue.  Ideally, things should end up looking the same regardless of if they're wrapped or not.
