### ISSUE TITLE
.is-active Active Class

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#283]
# Description

*Tell us all about your problem or feature proposal.*
Allow users to use is-active in addition to active classes. This will allow Drupal 8 theme developers to use the components more effectively.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
Hmm.  This seems like an opportunity for a feature like that in `byu-search`, where we modify our selector logic based on an input from the user.  We don't really want to support too many classes as marking the 'active' nav link, as each class we support adds the potential for a conflict with a class that doesn't actually mean what we think it means in the consumer's context.

Hmmm.  Let me ruminate on how it would work and come up with a proposal.
