### ISSUE TITLE
Menu links need option for flex spacing instead of just fixed width.

### ISSUE THREAD

**Issue by mbusch3** [byuweb/byu-theme-components#284]
# Description

We need a menu that doesn't force buttons to be the same width. We have some menu items with long names and other with short ones, and when we get 5 or 6 buttons, the text gets truncated at certain screen sizes. We've used the "long-link" class, but since that class takes so much space, every time we made one link long, it truncated another, which had to be made long, until all 6 were.

We've already discussed the issue with department heads, and have shortened the link titles from what they were to the shortest options they were willing to accept.

We'd like to be able to do what the gradstudies.byu.edu site has done (I think they cheated and used an older version of the theme).

[http://morgan-dev.byu.edu/img/menuwidth.png](http://morgan-dev.byu.edu/img/menuwidth.png)

# Websites Affected

Our current dev site is greenteam-dev.byu.edu for reference.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
*** This does not conflict at all with the specifications listed on brand.byu.edu, but allows a greater variety of sites to actually use the specs.
***** **AS A MATTER OF FACT, IF YOU LOOK AT THE HEADER IMAGE AT** [brand.byu.edu](https://brand.byu.edu/guidelines/web/), **IT HAS THIS FEATURE!**
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
In the engineering meeting on 8/1/17 we decided:
- We will use flex box so the browser adjusts the menu
- We will still have a cap of six links
- There will be a de facto character limit. The nav bar will have a fixed character limit.
- Leave links left aligned if there is less than four menu items

**Comment by bmorgan296** [comment]
Fixed in #291
