### ISSUE TITLE
Request: Allow the blue main header to be full-width and menu content-width

### ISSUE THREAD

**Issue by mbusch3** [byuweb/byu-theme-components#285]
# Description

In the current drupal 7 theme, we can't divorce the width of the main (blue) header from the links below it; either they are both full-screen, or they are both content-width. Our original design specs ask for a full-width main header with a content-width menu. Why can't we do this?

# Websites Affected

All drupal 7 sites.

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
*** **Please note that the example header at [BYU Brand](https://brand.byu.edu/guidelines/web/) does this.**
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
So I've been digging through Slack looking for the original specs, and in some of the older specs the menu isn't left-aligned with the B in BYU but instead with the site title. Beyond that I don't see any mention of a full-width title and a constrained-width navigation. 

The max width was requested by Aleni back in issue #62, and while it wasn't written in her request I believe during the discussion we had with her it was specified that with a constrained width menu the left edge of the first link should be aligned with the left edge of the 'B' in "BYU".

While I can't speak for the design team, I'd argue against what you're proposing because 1) the BYU logo and site title are both links and further separating them from the rest of the navigation and 2) I don't think it looks very good on wide screens, and on smaller screens it's a non-issue. 

For example, here's how it would look on a wide screen: 

![image](https://user-images.githubusercontent.com/19493582/28632991-84446adc-71ef-11e7-9bfd-ffcae0090943.png)

On screens of 1200px or less it's the same as the current implementation:

![image](https://user-images.githubusercontent.com/19493582/28633094-d97956b6-71ef-11e7-956b-b121ab2c5b3f.png)

For these reasons I'm inclined to deny this request. We discussed this in our engineering group meeting yesterday and the general consensus was that we'd prefer not to go this route, but we'll get confirmation from the design group before making a final decision.

I'm curious if this request is due to a specific use case or just your preference. If there's a specific situation where this is necessary it would help us to understand the request better.

**Comment by mbusch3** [comment]
The only reason I brought it up initially is that for our individual site, the design and mockups used the variable-width design, and I found it frustrating that it was impossible to implement with the seemingly-arbitrary restrictions built in the theme.

You're absolutely right that at lower resolutions, the point is moot. Once screens are less than 1200px wide, it all lines up anyway.

HOWEVER, the enhancement is designed for larger screens, anyway. Of the two options currently available, full-width tends to look ridiculous at those higher resolutions, which leaves us with a fixed-width option. Your first example picture seems pretty skewed (are you using a massive 4k monitor?). Mine feels awfully big, and it's maximum width is 1920px, which looks like this:

![wide1](https://user-images.githubusercontent.com/16626644/28639233-bf05eabe-7204-11e7-8643-f2c33d593756.png)

And if the menu were able to stretch to 1400px (functionality pending, but I think it should work soon), it would look positively great.

![wide2](https://user-images.githubusercontent.com/16626644/28639432-7e66f9ac-7205-11e7-84eb-6fcf257e30fb.png)

As far as UX rationale, it's fairly standard to have the search in the corner of the screen as opposed to somewhere in the middle. It's also fairly standard to have a header stretch all the way across the screen (please see the following niche sites on your massive screen: youtube.com, yahoo.com, bing.com, amazon.com). Based on your screen size and reasoning (and pic), the header really should look like this on high-res screens:

![ftfy](https://user-images.githubusercontent.com/16626644/28639875-ed7f1076-7206-11e7-935f-e5102517fe40.png)

That's not a bad option (see microsoft.com and ebay.com), but it may not necessarily be the only design that works or works the best for large screens.

**Comment by ThatJoeMoore** [comment]
These aren't "seemingly-arbitrary" restrictions, they are part the official BYU design spec.  Our job is to implement that spec, no more, no less.

**Comment by mbusch3** [comment]
I apologize if I came off a little too curt. I know you're doing your best within a rather strict set of guidelines.

I've got the same problem on my end: I've got a spec that I'm trying to implement, too. The reason that the limitation seemed arbitrary was that the BYU specs, as I found them [here](https://brand.byu.edu/guidelines/web/), seemed to support our design, while the theme implementation made our following that same design impossible.

**Comment by ThatJoeMoore** [comment]
Unfortunately, and this has been causing problems since day one, the images on the official site don't actually match the theme specs as delivered to us - they are screenshots that somebody took before the implementation actually matched the spec.

Yeah.  Tell me about it.

I'm not necessarily opposed to this proposal, but it's up to the design group, and the lead designer is out of town for a few weeks on her honeymoon.  Once she gets back, we'll be able to get a firm yea or nay on the proposal.

**Comment by mbusch3** [comment]
It there a place where I can see the actual specs? It would be nice to know what the actual constraints we have to work in are. Other than that, is there anything for me to do other than wait for the honeymoon to be over? (I've already stated my case in the Slack design-group channel, and I think it was you who sent me this way anyway...)

**Comment by ThatJoeMoore** [comment]
Alas, there isn't a publicly-available (or even privately-available) single document that has all of the specifications.  I've been pushing for such a thing, but haven't gotten any traction on it.

**Comment by mbusch3** [comment]
In other words, the best (only?) thing I have to go on is the brand.byu.edu site, which is outdated and has "screenshots that somebody took before the implementation actually matched the spec"???

:: sigh ::

Thanks anyway.

**Comment by ThatJoeMoore** [comment]
Yeah, I know.  It sucks, but I'm hoping we can make it better before too long.

**Comment by bmorgan296** [comment]
In the engineering on 8/1/17 we decided the following:
- The `max-width` for the blue header will be removed.
- It **will not** be an option to adjust the header width (so to keep branding patterns and lock-ups)
- The menu will stay fixed with
- The menu text will remain center aligned
- Menu width can be modified to match page width.

**Comment by kebowdog** [comment]
So I'm working on implementing this and had one more question: do we still want to allow the "full-width" attribute? In this context that would mean the navbar would stretch to fill the full width of the browser window (the same as the blue bar). Here's what that would mean:

With Full-Width Attribute:

![image](https://user-images.githubusercontent.com/19493582/28880555-af7c5cf0-7762-11e7-9492-0258a1a07143.png)

Without Full-Width Attribute:

![image](https://user-images.githubusercontent.com/19493582/28880597-ca51e48c-7762-11e7-8711-7bbf3ee25b16.png)

**Comment by bmorgan296** [comment]
I don't know what @Aleniras would say, but I would think so. I think having the full width blue header and the constrained width menu would allow consistent branding on all BYU sites. Also, if it wasn't consistent, then as users jump around sites, their menu bar size may change and that could get frustrating from a UX standpoint.

**Comment by ThatJoeMoore** [comment]
It's there, so we can't remove it without issuing a 2.0.  I might make the console log out that it's deprecated, though, when consumers set it.

This is one of those times when I wish we had some metrics on how many people are using what features...

**Comment by Aleniras** [comment]
metrics are always a great idea. what's the status on getting those set up?

I don't think it's necessary to have full width options on the nav bar going forward. The times when full width works the best is with the smaller desktop screens, and in many cases the set width/default width will already look "full width" at that point.

**Comment by kebowdog** [comment]
Ok, so in the absence of metrics I'll log out a message saying "The full-width attribute has been deprecated as of version 1.1.2 of the BYU Theme Components and is not recommended" and otherwise leave it in place.

**Comment by ThatJoeMoore** [comment]
I'd say make it version 1.2.0.  We've already got a few things that are going to necessitate another feature release, plus I'd be loathe to make a change this big in a bugfix release.

**Comment by kebowdog** [comment]
Ok. I've updated the docs and a PR is on the way.

**Comment by GardinerMatt** [comment]
Hmm...I strong disagree with this commit.  It is kind of a style norm for the background color to extend to the edge of the screen, but for the headers/text to be in the middle of the page for easy access.  It just looks bad the other way.  I guess I'll stick to whatever the previous release was.

![screen shot 2017-08-30 at 10 12 36 am](https://user-images.githubusercontent.com/19825047/29883049-3aeee50e-8d6c-11e7-8a4a-860769cdccf9.png)

**Comment by kebowdog** [comment]
Yeah, I was also not a fan, though I'm slowly coming around. The decision was made after a lot of debate in the design and engineering groups. The nice thing is that the CDN is set up to allow targeting specific versions like you mentioned.

**Comment by ThatJoeMoore** [comment]
And yet, @kebowdog , that means that we now have to provide active support for multiple versions, which is something we really, really don't want to do.

**Comment by kebowdog** [comment]
Hmmm.... I didn't intend to make it sound like that was an option. So to be clear, if @GardinerMatt targets version 1.1.1 (the last version with the old header style) then he would not receive any new bug fixes, new features, etc. We're **not** going to release a version 1.1.2. If opinions are that strong on the subject then I'd recommend @GardinerMatt open an issue requesting we provide more options (i.e. a class or attribute that users can set to center the blue header).

**Comment by GardinerMatt** [comment]
I don't mind not getting new features, but what are we even versioning for if you don't get bug fixes?

**Comment by mbusch3** [comment]
@GardinerMatt @kebowdog When I originally submitted the bug, I was just looking for it as an option, not the default go-to only available option. I even agree that in some cases, the centered header might look better. My biggest complaint was that I hated that the theme forced only one option, and the way that the padding works on the menu, the alignment between the "BYU" of the blue header and the right-indented text of the first menu button looked awful.

As mentioned in my really long comment-with-pictures above, it's NOT cut-and-dry. Sites like amazon.com and yahoo.com use full-width top headers above content-width pages, while others (like microsoft.com and your github example) clearly don't, and wouldn't benefit from them.

My opinion: Options are good.

**Comment by GardinerMatt** [comment]
It doesn't bother me for Amazon becase they've got a lot of content in their header  We've basically got the title and the logout.  It leaves a lot of blank space.

![screen shot 2017-08-30 at 10 57 26 am](https://user-images.githubusercontent.com/19825047/29885043-8beb04f0-8d72-11e7-80d5-13f7b5dc9411.png)

![screen shot 2017-08-30 at 10 58 43 am](https://user-images.githubusercontent.com/19825047/29885048-8dd66462-8d72-11e7-8647-9b094211c7d2.png)

**Comment by ThatJoeMoore** [comment]
I'm saying screw it.  I've got a PR in the works that makes the new look optional.  I don't care what the "design group" says, since there is no more "design group", there's just a single designer.

**Comment by GardinerMatt** [comment]
I'll live with whatever you do, I was just giving my 2 cents.  Good luck.

**Comment by mbusch3** [comment]
@ThatJoeMoore Bless you and bless your children's children's children. Thank you for making this an option!

**Comment by ThatJoeMoore** [comment]
See #312
