### ISSUE TITLE
[Documentation] Add sticky footer documentation to Footer.html

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#288]
# Description
Right now the index.html of the documentation has a description of sticky footers and how to implement it, but the footer does not. Since people often consider "sticky footer" to be a footer component problem we should probably have a link or a mention on the footer page directing them to the correct place.

# Websites Affected
http://2017-components-demo.cdn.byu.edu/

**Comment by ThatJoeMoore** [comment]
We should also make sure we use `flex-grow: 1` instead of `flex: 1`.
Anybody want to guess which browser might have an issue with it? 😫

**Comment by rburkey87** [comment]
Ooh ooh! Pick me! Is it... Internet Explorer? hahaha

**Comment by kebowdog** [comment]
I totally already knew that..... (furiously updates production code).
