### ISSUE TITLE
Setting the z-index

### ISSUE THREAD

**Issue by ashton314** [byuweb/byu-theme-components#299]
# Description

I would like to set the z-index of the header. I do not see any way to do this. Can this be added as a feature, or, if it exists, be documented?

# Issue Type

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

# Web Site Platform

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
You should be able to just use normal CSS to accomplish this:

```css
byu-header {
  z-index: 2;
}
```

Is that not working?  If it isn't, could you explain more of what you're trying to do so that we can replicate the problem?

**Comment by ashton314** [comment]
Okay, I've got an element with class `.sidebar` that's covering the header. Here is the relevant CSS code:

    byu-header {
        z-index: 2;
    }

    .sidebar {
      position: fixed;
      top: 0px;
      bottom: 0;
      left: 0;
      z-index: 0;
      padding: 20px;
      padding-top: 110px;
      overflow-x: hidden;
      overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
      border-right: 1px solid #eee;
    }

And the relevant HTML:

    <byu-header full-width>
      <span slot="site-title">Printing Services</span>
      <byu-menu slot="nav" collapsed>
        <a data-target="dashboard" class="selected" href="#">Dashboard</a>
        <a data-target="print-jobs"  id="print-jobs-link" href="#">Print Jobs</a>
        <a data-target="printer-supplies" id="printer-supplies-link" href="#">Printer Supplies</a>
        <a data-target="notifications" href="#">Notifications</a>
        <a data-target="settings" href="#">Settings</a>
      </byu-menu>
    </byu-header>

    <div class="container-fluid">
      <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
        <h3>&nbsp;Menu</h3>

        <hr />

        <div class="contextual-content dashboard">
          <ul class="nav nav-pills flex-column scope-selector">
            <li class="nav-item">
              <a class="nav-link active" data-scope="dashboard-main" href="#">Main Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-scope="dashboard-help" href="#">Help</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-scope="dashboard-api-docs" href="#">API Documentation</a>
            </li>
	  </ul>
      	</div>
    ...
      </nav>
    </div>

What this looks like:
![screen shot 2017-08-09 at 3 58 24 pm](https://user-images.githubusercontent.com/2874507/29145886-121128d2-7d1c-11e7-81f0-16d3c4474f8a.png)

**Comment by ThatJoeMoore** [comment]
Have you tried adding a `position: relative` to `byu-header`?  `z-index` doesn't do anything unless you've positioned the element, and `relative` will let us position it without moving it.

**Comment by ashton314** [comment]
Okay; since I've got a fixed navbar on the left side, the header only flows over the navbar if I use the same positioning context. (I.e. in this instance `fixed`.) Okay, I'm on the right track now. Thanks!
