### ISSUE TITLE
Long Menu Link Padding

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#300]
# Description

Now that we're using flexbox for the menu, the padding for long menu links looks uncomfortably small. This may be something to ask @Aleniras about.

<img width="238" alt="screen shot 2017-08-11 at 8 32 00 pm" src="https://user-images.githubusercontent.com/9389424/29237112-72ca9dfc-7ed4-11e7-9f52-ca16cc809cdc.png">

# Websites Affected

[asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
@Aleniras The padding is currently at 6px.

**Comment by Aleniras** [comment]
@bmorgan296 Lets increase to 9 please.

**Comment by rburkey87** [comment]
@Aleniras - The 6px padding is actually overridden further down. It's currently at 12px, but I think it looks much better with 15px.

**Comment by Aleniras** [comment]
@rburkey87 Thanks for your input -- could you send me some screenshots?

**Comment by rburkey87** [comment]
BEFORE
![image](https://user-images.githubusercontent.com/25965299/30608005-3cac4616-9d34-11e7-96dc-953a1c1e6556.png)

AFTER
![image](https://user-images.githubusercontent.com/25965299/30608033-4fd1e552-9d34-11e7-9a35-ebc370bc66ce.png)

**Comment by rburkey87** [comment]
Hmm... just realized I'm looking at the more menu link and the link is present twice already in the menu bar. In the menu bar, mine shows a significant amount of padding at all screen widths

![image](https://user-images.githubusercontent.com/25965299/30608190-ce17d444-9d34-11e7-8530-59c4f200b9c6.png)

**Comment by rburkey87** [comment]
@Aleniras - Actually, I think the 12px looks fine. Unless this is an issue in a different browser, I'm not seeing any problems (already fixed?)

**Comment by rburkey87** [comment]
*sigh* I should get my things together before I type so I can be more concise... lol. The PADDING on the menu bar is only 6px, as Blake said, but the flexbox seems to be creating plenty of extra room around the menu items. I'm wondering if this was an issue before the flexbox was fixed. @bmorgan296 are you still seeing this issue?
