### ISSUE TITLE
[byu-footer] Left/Right Footer Margin

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#303]
# Description

This is another quetsion for @Aleniras: Is the padding supposed to be that small between the edge of the browser and the gray footer? I know it seems like no one would noticed this because they won't be resizing their browser, but if they're like me and sometimes have their browser this width, they may notice it.
<img width="1049" alt="screen shot 2017-08-19 at 3 16 49 pm" src="https://user-images.githubusercontent.com/9389424/29490215-4c59ed66-84f2-11e7-9a92-d7ab15b5074e.png">

# Websites Affected

- [asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)
- [photo-dev2.byu.edu](https://photo-dev2.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [x] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by Aleniras** [comment]
@bmorgan296 I'd like there to be more padding yes. Unfortunately, it looks like if we did that it would force "Affiliated Speeches" (or other long titles) to two lines, correct?

**Comment by bmorgan296** [comment]
@Aleniras That depends. If you want more padding between the columns, then we could just increase the padding and have the footer break into two columns and two rows sooner. The other option is to just increase the padding on the far left and far right sides of the footer to be equal with the current padding between columns. Which would you prefer?

**Comment by bmorgan296** [comment]
We decided to just make the outer padding equal to the column spacing.

**Comment by rburkey87** [comment]
Yeah, it changes to that when it stacks 2x2. I'll make it happen on the 4x1
