### ISSUE TITLE
[byu-header] page load jittering

### ISSUE THREAD

**Issue by dbluhm** [byuweb/byu-theme-components#304]
# Description
The nav menu in byu-header jitters pretty noticeably on page load. It doesn't appear to happen on every page load but is fairly consistent. Messing with other sites that implement the new theme, I am unable to reproduce the same behavior on all of them so I'm not positive if this is an issue with the theme components or not. Your direction will be greatly appreciated.

![jittering_nav](https://user-images.githubusercontent.com/22032832/29577287-17356466-8728-11e7-9e5e-f2535cfcdfdb.gif)

# Websites Affected
https://web3.fsl.byu.edu
https://brand.byu.edu also seems to have issues.

# Issue Type
- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform
- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by dbluhm** [comment]
![more_jittering_nav](https://user-images.githubusercontent.com/22032832/29577762-dd928548-8729-11e7-9969-07510e3e4ac4.gif)
Another gif taken from brand.byu.edu

**Comment by ThatJoeMoore** [comment]
To some extent, this is inevitable, as the fact that you don't see this on other pages is due to browser optimizations that help lessen it.

That said, we really shouldn't be seeing this.  We do have a stylesheet that gets loaded alongside the components to help prevent this sort of thing (that's one of the reasons for importing the `byu-theme-components.min.css` stylesheet), but I've noticed that it seems to have some issues.  We'll need to dig in and see what's happening there.  It's also possible that there's some sort of timing issue in the component startup that's making it take longer than it should to stamp its template.

**Comment by GardinerMatt** [comment]
I don't know if this helps, but I was referencing JQuery from Google's CDN in the middle of loading the BYU-Web components requirements and it caused this issue.  By moving external dependencies after the web-components references, this was fixed for my projects.

Changing
`  <link type="text/css" rel="stylesheet" href="https://cloud.typography.com/75214/6517752/css/fonts.css" media="all" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.byu.edu/byu-theme-components/1.x.x/byu-theme-components.min.css" />
  <script async src="https://cdn.byu.edu/byu-theme-components/1.x.x/byu-theme-components.min.js"></script>`
to
`  <link type="text/css" rel="stylesheet" href="https://cloud.typography.com/75214/6517752/css/fonts.css" media="all" />
  <link rel="stylesheet" href="https://cdn.byu.edu/byu-theme-components/1.x.x/byu-theme-components.min.css" />
  <script async src="https://cdn.byu.edu/byu-theme-components/1.x.x/byu-theme-components.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>`

**Comment by ThatJoeMoore** [comment]
I don't think it actually fixed it, it just made the jitter so fast that it
doesn't actually get rendered. Digging around, it looks like out Flash of
Unstyled Content rules (which are meant to prevent that jitter) are, well,
completely borked.

**Comment by rburkey87** [comment]
@ThatJoeMoore - I might need to update the FOUC styling. It's been a while.

**Comment by ThatJoeMoore** [comment]
This is addressed by #328
