### ISSUE TITLE
[byu-menu] Font size in mobile doesn't match the theme.

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#306]
# Description

The font size in mobile seems to not match the rest of the font size. @Aleniras: should it be the same size at the use text in mobile?

![img_0160](https://user-images.githubusercontent.com/9389424/29670270-607a2d38-88a3-11e7-99af-9a052e9f8017.PNG)

# Websites Affected

[asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Safari for iOS
- [x] Chrome for iOS
- [x] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
Which font size are you talking about?

**Comment by bmorgan296** [comment]
Menu links.

**Comment by Aleniras** [comment]
Great catch @bmorgan296. Yes, please shrink the font size of the links to match "sign out"

**Comment by Aleniras** [comment]
Also, whenever text runs over two lines it should look like the attached. (i.e. 2 lines of page title = height of 1 "U" in BYU.)

![image](https://user-images.githubusercontent.com/26605197/29674409-59d3601a-88af-11e7-8121-a65bc25199f9.png)

**Comment by Aleniras** [comment]
Here it is from the spec sheet: 

![image](https://user-images.githubusercontent.com/26605197/29674553-b90dd16e-88af-11e7-8aa6-1b862b0cdcf9.png)

**Comment by ThatJoeMoore** [comment]
@Aleniras We've talked about this before; that's simply not possible when the main header flows onto two lines.  There is no way to dynamically size text based on how many lines it's going to flow onto.  Making the main title and subtitle do that, though, is something that should already be happening.

**Comment by Aleniras** [comment]
Great. Thanks!

**Comment by ThatJoeMoore** [comment]
Actually....I really should think more before saying something's impossible.  We might not be able to have the font size change, but we might be able to pull off some interesting things with line-height....hmmm.

**Comment by Aleniras** [comment]
Ha, alright. Well if the title line height is a quick fix lets do it. Otherwise lets wait til we get final instruction from President Worthen for what things will look like going forward. As for the links though, we should change those to match the size of the signout, as listed above.

**Comment by ThatJoeMoore** [comment]
Yeah, we'll track the possible site-title changes in another issue.

**Comment by bmorgan296** [comment]
This issue can't be replicated again. It was a wierd fluke...
