### ISSUE TITLE
[byu-footer] Footer text color change.

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu-theme-components#307]
# Description
In the homepage redesign meeting, @Aleniras as for there to be a color differentiation between links and text in the gray footer. Text black, links dark gray.

<img width="619" alt="screen shot 2017-08-24 at 2 37 13 pm" src="https://user-images.githubusercontent.com/9389424/29687460-c66539a4-88d9-11e7-95b9-3cd29b7cd109.png">

# Websites Affected

[https://asb-ucom-dev2.byu.edu](https://asb-ucom-dev2.byu.edu)
BYU Test Homepage

# Issue Type

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [x] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Safari for iOS
- [x] Chrome for iOS
- [x] Firefox Mobile for Safari
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [x] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by bmorgan296** [comment]
@Aleniras I made the change, and it all looks good except phone numbers. Different bowsers treat phone numbers differently. Most browsers treat phone numbers as plain text, but Safari on iOS treats it like a link and Edge underlines it. What would you like to happen?

**Comment by Aleniras** [comment]
@bmorgan296 thank you! your speed is amazing. I think its best to have phone numbers as a link (esp. on mobile devices) so they can dial by clicking it.

**Comment by rburkey87** [comment]
@bmorgan296 - is this issue closed?

**Comment by bmorgan296** [comment]
Yes. This has been fixed.
