### ISSUE TITLE
Specify line height in footer to avoid override

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#315]
# Description

Blake found this issue, revealed by the new d8 theme: https://github.com/byuweb/byu_d8/issues/18
If the theme in use has a line-height set generally, then it has too much space in the blue byu footer. 

If we add `line-height: 12px;` (or 14px if that's better) where we have `font-size: 12px`  under 

`.university-footer { ... }` then it should be fixed.
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/12898896/30178097-092cc6e4-93c5-11e7-838e-9420dac00df1.png)

# Websites Affected
it was revealed i the d8 theme, on photo-dev and the new byu.edu homepage.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
https://photo-dev2.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*
actually slight difference across platforms/themes if they set a line-height
- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
(all - not browser specific)
*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [X] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #333
