### ISSUE TITLE
Adjust menu link and link hover/active background color with menu is transparent

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#317]
# Description

This issue was spotted with the d7 theme:
https://github.com/byuweb/byu_d8/issues/13
When menu is set to transparent, the link itself is also transparent so it looks lighter than navy:
![image](https://user-images.githubusercontent.com/12898896/30288644-c0911d84-96e6-11e7-8212-0612d124a4e9.png)
Also affects the gray background for active/hover.

We are setting the menu to be transparent but not specifying information for the link or link background. We need to adjust to the specs aleni posted:
![image](https://user-images.githubusercontent.com/12898896/30288619-af433cec-96e6-11e7-97f3-06a60894d0c4.png)

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
(all browsers)
*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers
(not browser specific issue)
- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [X] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by rburkey87** [comment]
I think we decided that this would be fixed if the "transparent" class applied to the background of the individual menu items instead of applying to `<byu-menu>` entirely, as it currently does.
