### ISSUE TITLE
[byu-footer-column] content not aligning correctly outside Chrome

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#320]
# Description
Footer column content is aligning right in Firefox, Edge, and IE11. May be a Drupal 7 issue. Can someone verify if it is/is not happening in a custom build?

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/25965299/30754909-d3fd0dd0-9f81-11e7-83e5-daba1b386856.png)

# Websites Affected
https://calendar-test.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [?] Apple Safari
- [x] Microsoft Edge
- [x] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [x] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by rburkey87** [comment]
@kebowdog - can you verify if this is happening on one of your (non-Drupal) sites?

**Comment by kebowdog** [comment]
@rburkey87 Sorry about the slow response, I haven't seen this happen on any of our sites. You can look at http://exsc-new.byu.edu/ or http://hs.byu.edu/ for examples of it working as expected.

**Comment by rburkey87** [comment]
@kebowdog - thanks! It's probably a drupal 7 issue then
