### ISSUE TITLE
Remove font call in menu - causing duplicate billing to Hoeffler

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#321]
# Description
A reference to the fonts is still included in byu-menu.html.
This means that if someone includes the different font package, we are being billed twice/it is counting twice and adding up. This is very likely why we hit and passed our plan limit for the Hoeffler fonts recently.
I have checked that this font reference isn't needed. Kevin also has confirmed it.
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/12898896/30881457-25de6f1a-a2c3-11e7-8412-ff7d6b422c4a.png)

# Websites Affected
Homepage (was affected, we took it out in our own), speeches.byu.edu, Calendar.byu.edu and any other website that is referencing the Full font package and the components.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
Hey!  I noticed this today, and was just gonna dig in and find the reference!  Great minds, right @katrialesser ? 😉
