### ISSUE TITLE
Change BYU footer scss file to use mixins

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#331]
# Description
The other components use mixins but the byu-footer component doesn't. I believe it was just missed when we reorganized.

This wouldn't change any styling, just change it to use mixins which is our format. 

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

# Websites Affected
NO VISIBLE IMPACT
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?
CODE FORMATTING
# Browsers Affected
NOT BROWSER SPECIFIC although this change will be good for our flash of unstyled content and as we make changes, etc. 
*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
I intentionally did that when we redid the footer. The way people have been aggressively putting everything into the mixins is not a great idea - it ought to just be the things that are common between the 'extra' styles and the component styles. It makes debugging and refactoring a lot harder to have every single style be in the common stylesheet.

**Comment by blakemorgan** [comment]
Should we change all the other components to match the current organization of the footer styles then?

**Comment by ThatJoeMoore** [comment]
At some point, probably.  I think what we should work on before then is a formal style guide for writing our components, then working on making everything match that style guide.
