### ISSUE TITLE
If footer button text can't fit, the line height is way too big

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#332]
# Description
When I clicked the checkbox for extras it added a 5th column and there was less room for the footer button. We should probably allow our buttons to be flexible and work for two lines of text.

*Tell us all about your problem or feature proposal.*
Button shouldn't be a set height but should use padding and have a small enough line height so that it fits and looks okay.

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/12898896/32251137-5771d460-be55-11e7-9023-f949f4dbec65.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
Found testing with example Every Feature Demo page.
# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers
Not Browser specific.
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*
Not relevant.
- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Fixed via PR #335
