### ISSUE TITLE
[byu-search] Search button border radius

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#337]
# Description

*Tell us all about your problem or feature proposal.*
In a Chrome update, they added a default border radius around objects with no border radius assigned. A border radius of 0 needs to be added to the search button.

<img width="230" alt="screen shot 2017-11-23 at 2 22 56 pm" src="https://user-images.githubusercontent.com/9389424/33186746-0df57104-d05a-11e7-9acc-acf60a4c2444.png">

# Websites Affected

[photo.byu.edu](https://photo.byu.edu)

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by katrialesser** [comment]
@blakemorgan which chrome update/version? I don't see it on mac chrome just for the record. I agree we should do this, just letting people know it may only be windows chrome.

**Comment by katrialesser** [comment]
nevermind (they already fixed it so i couldn't reproduce)
