### ISSUE TITLE
[byu-search] Too much padding in desktop Safari.

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#341]
# Description

There is too much padding in the desktop Sarafi search.

**Wrong (Safari):**
<img width="255" alt="safari search" src="https://user-images.githubusercontent.com/9389424/33406216-0b4552c0-d529-11e7-9696-474b2dfb1b9b.png">

**Right (Chrome):**
<img width="236" alt="chrome search" src="https://user-images.githubusercontent.com/9389424/33406224-13171a10-d529-11e7-9028-025e82008d7f.png">

# Websites Affected

- https://typo1.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
This issue is caused by default settings of Safari. They can't be overridden by zero or negative padding. We need `padding: 0` for the search box only when in Safari.

**Comment by ThatJoeMoore** [comment]
You might try using `::-webkit-input-placeholder` to style things?  That may not work, however, as Safari just plain won't let you style input[type=search] very much.  If we can't get the padding fixed with the above pseudoclass, we'll have to close this as a wontfix, because Safari is apparently determined to become the new IE.

**Comment by ThatJoeMoore** [comment]
Oooh!  I just found something!  Try adding this:

```
input[type="search"] {
      -webkit-appearance: textfield;
    }
```

Supposedly, that tells Safari to let us just style the dang thing ourselves.

**Comment by blakemorgan** [comment]
I tried 
```css
::-webkit-input-placeholder {
  padding: 0;
}
```
with no avail and the other fix didn't work. Closing as wontfix.
