### ISSUE TITLE
[byu-footer] Phone number link not styled as other links in Edge & iOS.

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#342]
# Description

We need @Aleniras to confirm how phone number links should appear in the gray footer. It is currently different than all other links.

<img width="252" alt="screen shot 2017-11-29 at 5 21 16 pm" src="https://user-images.githubusercontent.com/9389424/33406385-dc70d7ac-d529-11e7-94f3-9de68b4bb96a.png">

# Websites Affected

- https://typo1.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [x] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by Aleniras** [comment]
Thanks for catching this @blakemorgan. Please format it as all other links are formatted and include the hover.

**Comment by blakemorgan** [comment]
After further research, the link will be styled correctly. It is the responsibility of the engineer to designated the link as a phone link. For example:
```html
<a href="tel:+01-123-456-78909">123-456-7890</a>
```
