### ISSUE TITLE
BYU Footer Action Button filling 100% height

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#345]
# Description
BYU Footer Action Button has height: 100% !important, causes it to fill page height.

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/19493582/34118237-7819c424-e3db-11e7-96e8-3f372dea6d34.png)

# Websites Affected
https://exsc.byu.edu/, http

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

Affects all browsers

**Comment by blakemorgan** [comment]
Fixed in #346
