### ISSUE TITLE
User's name is truncated if longer than 13 characters

### ISSUE THREAD

**Issue by cache117** [byuweb/byu-theme-components#357]
# Description
If the logged-in user has a name that is longer than 13 Characters (e.g. "Angela Murdock" which is 14 characters long), it is truncated. Here is an example:
![image](https://user-images.githubusercontent.com/11652513/39717849-b5390a66-51f1-11e8-8cf2-63366c76089e.png)

If I change the name to "Angela Murdoc" (exactly 13 characters long), it displays the whole name:
![image](https://user-images.githubusercontent.com/11652513/39717983-1cf8ebbc-51f2-11e8-9170-dd6e98bb685d.png)

This is not ideal, and "Angela Murdo..." is longer than the user's name anyways! We always have a lot of real-estate in the top banner, and even when on a mobile device, the name is removed from the banner and placed in the menu, so there should be more than enough room for most names. And even if you can't accommodate all names, it should be able to be more than 13 characters.

# Websites Affected
We recently implemented this in HR PeopleSoft, but it is only available on our non-Prod websites.

# Issue Type

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

I didn't try any other browsers.

## Mobile Browsers
This is not a problem on Mobile, because the user info flows into the More menu, and it displays the full name properly there.

# Web Site Platform

*What is hosting your website?*
- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

As mentioned before, this is being done in PeopleSoft. Because of this, we have little or no control over the underlying HTML for this, so we are resorting to various non-standard ways of applying the BYU Web Components.

**Comment by ThatJoeMoore** [comment]
It's actually not 13 characters, it's 130px. (You can see that `max-width: 130px` gets set).  

Unfortunately, this is imposed by the current design spec, and isn't something we can decide to change.  The reasoning behind it, I believe, is that there are both sites and students with very, very long names, and we have to accommodate that in the design, especially when there is also a search bar present.  It may be, however, that 130px is too small a width, and we may want to have that width actually be based off of the width of the screen.

Now, don't tell anybody that I told you this in a public forum (oh...wait...), but you can set `max-width` to a different value on the user name element to change the specifics behavior. You could even do something as blasphemous as `max-width: unset` ;)

**Comment by cache117** [comment]
Huh... I didn't think to try that:
![image](https://user-images.githubusercontent.com/11652513/39728901-6c41cd5a-5216-11e8-9a16-b6d01164ac49.png)

Awesome! Thanks! We'll keep it reasonable.

**Comment by kebowdog** [comment]
Given that there's a workaround for this I propose we close it for now. If we really want to pursue it I suppose we could look up what the longest name on campus is, but since no one's brought this up in months I think it may not be worth pursuing.
