### ISSUE TITLE
Search icon is missing in safari on ipad 9.3.5

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#358]
# Description
The search icon is missing in Safari on ipad 9.3.5
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/12898896/40686173-a6445c68-6353-11e8-9d16-7961215dc1d3.png)

# Websites Affected
Noticed on the BYU Homepage and news.byu.edu

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
news.byu.edu
# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [X] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [X] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*
Not specific to drupal
- [X] Drupal 7
- [X] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Given that we're currently on iOS 12 and only supporting the most recent 2 versions of each browser I'm closing this one.
