### ISSUE TITLE
Menu link min-width causes scrolling between 1024 px and 1200px

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#360]
# Description

*Tell us all about your problem or feature proposal.*
When there are six items in the menu and the screen is between the mobil-max-width (default 1024px) and 1200px the page gets a horizontal scrollbar.

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/19493582/41548757-12f16c6a-72e1-11e8-8ba0-25f390204109.png)

# Websites Affected
https://ndfs.byu.edu/, but you can see it on any site with six or more links in the menu.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox (though it's not as wide a range of widths)
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] DNN
- [ ] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #369
