### ISSUE TITLE
mobile username color is not accessible

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#362]
# Description
The username (linked or text) is light blue on desktop, over the navy background. On mobile it is over a white background, and the specs say it should be navy. It is not right now.

*Tell us all about your problem or feature proposal.*
Need to adjust and fix the color for mobile.

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/12898896/41618156-94102924-73bf-11e8-962f-7c57139245bc.png)

# Websites Affected
calendar.byu.edu
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
You have to be able to login to see the username, but calendar.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [X] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [X] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [X] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #369
