### ISSUE TITLE
Update the royal color

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-theme-components#363]
# Description
Apparently the royal color was updated; I don't think we were alerted when this change was official, but it is there now. 
https://github.com/byuweb/byu-theme-components/blob/master/components/shared-styles/colors.scss
should be updated:
https://brand.byu.edu/guidelines/color/
royal: #0057B8
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
Color hex code tweak, will affect royal anywhere on websites with header/footer. Used on some link hovers.

# Websites Affected
any/all
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
new color: 0057B8
https://brand.byu.edu/guidelines/color/
# Issue Type

*Is this (add an x in the boxes that apply)*

- [X] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Safari for iOS
- [ ] Chrome for iOS
- [ ] Firefox Mobile for Safari
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #369
