### ISSUE TITLE
href nested in slot="title" turns title blue

### ISSUE THREAD

**Issue by arzon94** [byuweb/byu-theme-components#381]
# Description
href="#' nested in slot="title" turns title blue
*Tell us all about your problem or feature proposal.*
style change to remove link styling
**If the issue is with styling, please include screenshots!**

<img width="341" alt="screen shot 2018-10-09 at 11 50 48 am" src="https://user-images.githubusercontent.com/16659722/46688100-c1772780-cbb9-11e8-969b-1621d2987930.png">

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
This was working at one point, and is a pretty common pattern, so we might consider this a blocker for release.
