### ISSUE TITLE
[byu-search] Search on header page has the placeholder attribute in the wrong place.

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#382]
The search examples on the header page of documentation put the `placeholder` attribute in the `<byu-search>` element. That will not work. It needs to be in an `<input>` tag.

**Comment by blakemorgan** [comment]
This is not a documentation error. This is a bug in the components. Users shouldn't have to create an input field with the `<byu-search>` element. The `placeholder` attribute should be passed from `<byu-search>` to the input field in the shadow root.

**Comment by blakemorgan** [comment]
Oh okay. I didn't know that. In that case, I think we should revert this issue and just remove the `placeholder` attribute that is in the `<byu-search>` tag in the documentation.

**Comment by ThatJoeMoore** [comment]
I mean, I'm actually fine with changing that for the placeholder - it is a use case that makes a lot of sense.  But we also need to address some faulty logic in the ifs that power this feature.

**Comment by ThatJoeMoore** [comment]
Hmmm...I'm especially OK with keeping the feature in place since it looks like the D8 theme might be relying on it.  And, if it was already documented, I don't want to pull a Lucy to other developer's Charlie Brown.

![Charlie Brown](https://media.giphy.com/media/jKjN2TBAHsgzS/giphy.gif)

**Comment by kebowdog** [comment]
Fixed in #439
