### ISSUE TITLE
Footer doesn't respond to custom `max-width` attribute.

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#384]
# Description

If I set the footer's `max-width` it doesn't change anything.

Max width 200px:
![screenshot from 2018-10-09 12-08-49](https://user-images.githubusercontent.com/9389424/46689136-64c93c00-cbbc-11e8-96ff-b05c419113d5.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
The footer derives its max-width value from the header. So this in an expected behavior (unless you're specifying the max-width in the header and not seeing it reflected in the footer)
