### ISSUE TITLE
half of mobile dropdown items inherit background color of body

### ISSUE THREAD

**Issue by arzon94** [byuweb/byu-theme-components#386]
# Description
half of mobile dropdown items inherit background color of body
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![screenshot_20181009-124331](https://user-images.githubusercontent.com/16659722/46692684-297f3b00-cbc5-11e8-89e0-b90e780c2166.png)

# Websites Affected
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

10.37.147.44:8081
asb-ucom-web3-l.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #377.
