### ISSUE TITLE
Action button hover text is same as background

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#387]
# Description

If there is a link nested in another element (like a <span>) in the action button, the text will remain
white when the hover effect is applied.

<img width="384" alt="screen shot 2018-10-09 at 2 24 48 pm" src="https://user-images.githubusercontent.com/455981/46696466-67815c80-cbcf-11e8-8c38-7e21fefd6c90.png">

**Expected**

![image 1](https://user-images.githubusercontent.com/455981/46696828-5dac2900-cbd0-11e8-9713-cdb1a3058bd2.png)

# Websites Affected

news.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [x] Don't Know

**Comment by ben-mur64** [comment]
We are also experiencing this at <ece.byu.edu>. 

Using the Drupal 8 theme.

**Comment by ThatJoeMoore** [comment]
Will be released momentarily in 1.3.1.
