### ISSUE TITLE
Site Title doesn't line up with BYU Logo

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#392]
# Description
Site Title doesn't line up with BYU Logo. Instead the BYU logo sits a little below it.

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**
The alignment should be like this, with the capital letters aligned with the BYU logo, and ascenders potentially going higher:

![image](https://user-images.githubusercontent.com/19493582/46703280-ade0b680-cbe3-11e8-890f-35c440166770.png)

Instead it looks like this: 
![image](https://user-images.githubusercontent.com/19493582/46703335-e08aaf00-cbe3-11e8-95bc-332be12e21b4.png)

# Websites Affected
All. For example, lifesciences.byu.edu

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by rburkey87** [comment]
it looks like it would work if we change
```.byu-header-root img.byu-logo {
    margin-right: 8px;
    padding-top: 19.5px;
    padding-bottom: 19.5px;
}```

to

```.byu-header-root img.byu-logo {
    margin-right: 8px;
    padding-top: 18.5px;
    padding-bottom: 19.5px;
}```
