### ISSUE TITLE
BYU logo disappears in other browsers

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#398]
# Description
BYU logo is disappearing on Firefox, Edge, and IE in the updated Drupal theme, but not on my HTML test site. 

*Tell us all about your problem or feature proposal.*
It's coming from the height being set and then padding pushing the image into nothingness (combined with Drupal's `box-sizing: border-box;` setting). If I switch it to margins, it works fine.

# Websites Affected

ux.byu.edu

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [x] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [x] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
Fixed in #397
