### ISSUE TITLE
Double-wide footer columns only span 1 column

### ISSUE THREAD

**Issue by demitrih** [byuweb/byu-theme-components#399]
# Description
I develop the websites for Dining Services in HTML. We have been using the BYU Header and Footer components to add the theme to all of our sites. With the new version of the BYU Components, the "double wide" feature in the footer is no longer supported in the same way. Instead of extending the column width two frames, it only extends the width 1 frame. 

Attached is our style guide. See section for "Footer with Location Map". 
The map should extend the width of 2 columns: 
[See our style guide here](http://dining.byu.edu/styleguide/footer.html)
[See our JS Fiddle here](https://jsfiddle.net/Diningweb/brht234j/)

![double wide web component](https://user-images.githubusercontent.com/34491406/46769765-ff537900-cca9-11e8-8bf4-dc329cd3a157.png)

# Websites Affected
All of our footers follow the same format:
[Cougareat](http://dining.byu.edu/cougareat/)
[Legends](http://dining.byu.edu/legends/)
[Cannon Center](http://dining.byu.edu/commons/)
[Creamery](http://dining.byu.edu/creamery/)
[Blue Line Deli](http://dining.byu.edu/blueline/)
[MOA Cafe](http://dining.byu.edu/moa/)
[Harveys](http://dining.byu.edu/harveys/)

# Issue Type
- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
We'll take a look at this.  I'm estimating a Friday release for the fix, but I've never been known to give accurate estimates - so let's say sometime between tonight and next week ;).

**Comment by ThatJoeMoore** [comment]
Looks like it's being caused by https://github.com/byuweb/byu-theme-components/blob/master/components/byu-footer-column/byu-footer-column-common.scss#L40 . I'm investigating why that line was added so we can make sure that fixing this issue doesn't cause another one.

**Comment by ThatJoeMoore** [comment]
@demitrih This just got released.  If you wait an hour or so or flush your browser cache, you should see the column's content be the right width.
