### ISSUE TITLE
[byu-footer] site-footer-wrapper fills 50px blank space when screen is less than 1024 pixels

### ISSUE THREAD

**Issue by arzon94** [byuweb/byu-theme-components#404]
# Description
site-footer-wrapper fills 50px blank space when screen is less than 1024 pixels
*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

<img width="315" alt="screen shot 2018-10-11 at 12 04 16 pm" src="https://user-images.githubusercontent.com/16659722/46833169-2a4ed300-cd65-11e8-9696-0e6d4279ebaf.png">
<img width="325" alt="screen shot 2018-10-11 at 12 04 53 pm" src="https://user-images.githubusercontent.com/16659722/46833170-2ae76980-cd65-11e8-9ebf-8e5e694f703f.png">

# Websites Affected
https://aims.byu.edu/
https://map.byu.edu
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [x] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [x] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by demitrih** [comment]
Just to clarify the scope of this issue, it affects all websites that use the `<byu-footer></byu-footer> `tag that don't have columns. This is also seen on the web components [demo site](http://2017-components-demo.cdn.byu.edu/byu-footer.html).
![site footer](https://user-images.githubusercontent.com/34491406/47103111-b2b4f400-d1fb-11e8-8fef-5a60aad10185.png)

**Comment by arzon94** [comment]
@demitrih thanks for clarifying. If you have any specific sites you manage (or browser or platform) affected, let me know and I will add them to the issue
