### ISSUE TITLE
[byu-header] Action Button Click Box

### ISSUE THREAD

**Issue by Gi60s** [byuweb/byu-theme-components#410]
# Description

The click box is limited to the text on action buttons that are added like this:

```html
<span slot="actions">
  <a href="#action-2">Nested</a>
</span>
```

This could probably be fixed by setting the `<a>` tag to `display: inline-block` then give it negative margins and padding to compensate for the margins.

# Websites Affected

All

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Fixed by #433
