### ISSUE TITLE
[byu-footer] Footer includes visible top and bottom borders

### ISSUE THREAD

**Issue by demitrih** [byuweb/byu-theme-components#411]
# Description
The footer component includes top and bottom borders on each letter. This is something very subtle, so I'm not sure if this was intentional or part of the design.

![screen shot 2018-10-15 at 9 22 03 am](https://user-images.githubusercontent.com/34491406/46968297-1a3e3880-d070-11e8-89f4-9097a4686659.png)
![screen shot 2018-10-15 at 9 28 25 am](https://user-images.githubusercontent.com/34491406/46968894-c16f9f80-d071-11e8-9991-1dbda1bca3a1.png)
*Red arrow added to show mark

# Websites Affected
All sites using the BYU Footer component

# Issue Type
- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected
## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform
- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
We need this image to be exported as a vector, not a bitmap wrapped in a vector.

**Comment by kebowdog** [comment]
Fixed in #440
