### ISSUE TITLE
[byu-footer] Double-wide footer column's line below header still only spans 1 column

### ISSUE THREAD

**Issue by matheusap** [byuweb/byu-theme-components#414]
# Description

A while back, there was an issue with double-wide footer columns not spanning two columns. While that issue was fixed, the line beneath the column title is still only spanning across a single column as shown below. This used to span across both columns on the previous version of the footer. 
![double wide line](https://user-images.githubusercontent.com/19192212/47445935-4bf18680-d777-11e8-9d53-18f6c5ac3a7a.png)

# Websites Affected

This is affecting all of the BYU Dining restaurant pages:
[Cougareat](http://dining.byu.edu/cougareat/)
[Legends](http://dining.byu.edu/legends/)
[Cannon Center](http://dining.byu.edu/commons/)
[Creamery](http://dining.byu.edu/creamery/)
[Blue Line Deli](http://dining.byu.edu/blueline/)
[MOA Cafe](http://dining.byu.edu/moa/)
[Harveys](http://dining.byu.edu/harveys/)

# Issue Type

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
We need to ask Aleni about what she wants.

**Comment by blakemorgan** [comment]
I got confirmation from @aleniras. With the new version of the components, the line should only stretch the length of one column. It works as designed.
