### ISSUE TITLE
Console error from D8 BYU Theme: Uncaught TypeError on 'placeholder'

### ISSUE THREAD

**Issue by morrisem** [byuweb/byu-theme-components#436]
# Description

Getting the following error in the console on every page when using the latest D8 byu_theme:  byu-search.js:307 Uncaught TypeError: Cannot read property 'placeholder' of undefined

# Websites Affected

rsc-test.byu.edu

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

rsc-test.byu.edu : any page

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ X ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ X ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment]
We've identified the issue.  We're anticipating rolling out a fix within a few days.

**Comment by kebowdog** [comment]
Fixed in #439
