### ISSUE TITLE
Mobile Search Renders Incorrectly on Edge

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#453]
# Description

*Tell us all about your problem or feature proposal.*
On edge the search input doesn't render correctly in the mobile dropdown

**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/19493582/62074702-8c979800-b200-11e9-8717-846ad860fc0c.png)

# Websites Affected

Index.html in the components repo

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in 430bddf02bfc7f21e578cfe17111a293e3ecbf94. There was a typo in the CSS.
