### ISSUE TITLE
[BUG] CMS styles overriding styles for slotted elements in the light DOM.

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#455]
# Description
Our CMS has some default styles that override the style on menu elements in the Light DOM.

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/19493582/62146184-1a7f8b80-b2b2-11e9-9282-3251fbdcf8d3.png)

# Websites Affected
http://batgirl.byu.edu/dnn9 (this is my development machine. It may not be reachable from other networks, but I think it should be available to anyone on eduroam or the BYU Wired Network). 

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [x] DNN
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Added `!important` to the menu styles so they can be overridden. @kebowdog If it is still an issue after I release 2.1.0, please reopen.
