### ISSUE TITLE
Logged in Mobile Menu

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#47]
Just need to adjust formatting a bit here

<img width="321" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24210915/304a3176-0ef0-11e7-9837-bc7640e1ad05.png">

<img width="401" alt="image" src="https://cloud.githubusercontent.com/assets/26605197/24211442/aab627e8-0ef1-11e7-94c3-19efdfcb4691.png">

**Comment by kebowdog** [comment]
It's looking better, but the font color on mobile is still off, the margin of the icon is wrong, and the the menu items and user name are not aligned.

**Comment by rburkey87** [comment]
@Aleniras - just verifying before I make changes... do you want any hover styling?

**Comment by Aleniras** [comment]
@rburkey87 Not for mobile. If they click on the item, the grey bar can appear behind (like it does on the desktop version), but few mobile devices have hover functionality at this point.  Thanks for checking!

**Comment by rburkey87** [comment]
@Aleniras - hahahaha, I just realized what a silly question that was. Hover doesn't work so well on touch screens, does it? lol

**Comment by Aleniras** [comment]
Just a reminder that the name should be #0057B8 when logged in. (see above for original design)

![image](https://cloud.githubusercontent.com/assets/26605197/24779753/771df0a0-1aef-11e7-9d49-3e25ce0b56d8.png)

**Comment by Aleniras** [comment]
@rburkey87 how is this coming? can you give me an update on the name and the line height?

**Comment by rburkey87** [comment]
It's ready! Just waiting for the PR to be approved and merged

**Comment by ThatJoeMoore** [comment]
Fixed in #157
