### ISSUE TITLE
Components don't match Brightspot Templates

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-theme-components#472]
# Description
Since the launch of Brightspot the Brightspot templates have become the de facto standard for BYU websites, but the components haven't been updated to match. We initially talked about waiting until the Brightspot templates were more settled in their design, so now may be a good time to look at this again.

*Tell us all about your problem or feature proposal.*
Specifically, the header needs to be a little taller, the navigation links should have a blue bottom border on hover/active, and potentially should support dropdowns. The footer on Brightspot is also larger.

**If the issue is with styling, please include screenshots!**
Components:
![image](https://user-images.githubusercontent.com/19493582/82943773-5b3e4480-9f57-11ea-89f5-f9a8929e753c.png)

![image](https://user-images.githubusercontent.com/19493582/82944023-bec87200-9f57-11ea-9555-46e31525498b.png)

Brightspot:
![image](https://user-images.githubusercontent.com/19493582/82943805-68f3ca00-9f57-11ea-99e8-b188a03c168b.png)
![image](https://user-images.githubusercontent.com/19493582/82943970-a9ebde80-9f57-11ea-84dc-702886efc358.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [x] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [x] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [x] Chrome for Android
- [x] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Fixed in #474
