### ISSUE TITLE
[BUG] active class isn't active

### ISSUE THREAD

**Issue by Michael4d45** [byuweb/byu-theme-components#476]
# Description
Menu links that have the class 'active' are no longer highlighted in version 2.1.X as it was in 2.0.X

Yes, I could include my own css, but I manage many websites and would be infeasible. 

![Screen Shot 2020-07-28 at 12 38 29 PM](https://user-images.githubusercontent.com/2423882/88707312-4ef97380-d0cf-11ea-88b2-0c5c224802d1.png)

![Screen Shot 2020-07-28 at 12 37 49 PM](https://user-images.githubusercontent.com/2423882/88707358-5a4c9f00-d0cf-11ea-9dc3-bce779413075.png)

Even on the web components website
<img width="566" alt="Screen Shot 2020-07-28 at 12 45 51 PM" src="https://user-images.githubusercontent.com/2423882/88708051-4e151180-d0d0-11ea-8771-8fa7960f682f.png">

# Websites Affected
All of them, I assume, that use 2.X.X

# Issue Type

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Apple Safari
- [X] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers
Haven't looked
- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [X] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Thanks for reporting this. @blakemorgan actually created a hotfix PR (#475) that addresses this issue, so we should be able to close this once that's merged and released.

**Comment by blakemorgan** [comment]
Fixed in #475
