### ISSUE TITLE
Footer Overflow on Firefox/Chrome  [BUG]

### ISSUE THREAD

**Issue by trey-wallis** [byuweb/byu-theme-components#477]
# Description

The footer overflows on the page

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/40307803/88839214-fd68eb80-d197-11ea-91ab-ae5726c5a122.png)

overflow-x: hidden; in the body tag solves the issue but I need overflow on my website

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [X] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
Thanks for posting. We are working on some accessibility issues that have been in the components since the beginning, so we will include this in that release.
