### ISSUE TITLE
[BUG] Script Error on Internet Explorer

### ISSUE THREAD

**Issue by evade-ninja** [byuweb/byu-theme-components#487]
# Description

*Tell us all about your problem or feature proposal.*
Script error on Internet Explorer

# Websites Affected
Technically this bug affects all websites using the BYU theme when viewed from Internet Explorer. The script error prevents Duo from working properly in CAS.

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [x] Other (please specify) Internet Explorer

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment]
Thanks for reporting this. My understanding was that the web advisory committee voted to discontinue support for IE since it represented such a small percentage of users on campus. (Especially since I'm pretty sure Edge can be installed on older versions of Windows now) Is there still a banner telling them to switch to a newer browser, or did that get taken down?

**Comment by evade-ninja** [comment]
Switching browsers isn't an option in this case, as their software is using the embedded internet explorer component which is what is choking on a script error.

**Comment by blakemorgan** [comment]
@kebowdog the banner was taken off in v2. But like you said, IE support was discontinued. I've added the wontfix label and am closing the issue.
