### ISSUE TITLE
[BUG] Web Components Demo site not scaling responsively

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu-theme-components#488]
# Description

Text isn't wrapping when viewed at tablet widths or smaller. Seems like the code snippets aren't wrapping and it's pushing out the width of the content while the header/footer scales down. 

![image](https://user-images.githubusercontent.com/25965299/97094207-f5421000-160f-11eb-8588-8a0780cc3669.png)

# Websites Affected

https://webcomponents.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by blakemorgan** [comment]
I looked into a bit and it looks like a flaw of the library we're using. Since it doesn't affect the actually components, I'm going to pass on fixing this.
